letters = {
    "a": "A*",
    "b": "PW*",
    "c": "KR*",
    "d": "TK*",
    "e": "*E",
    "f": "TP*",
    "g": "TKPW*",
    "h": "H*",
    "i": "*EU",
    "j": "SKWR*",
    "k": "K*",
    "l": "HR*",
    "m": "PH*",
    "n": "TPH*",
    "o": "O*",
    "p": "P*",
    "q": "KW*",
    "r": "R*",
    "s": "S*",
    "t": "T*",
    "u": "*U",
    "v": "SR*",
    "w": "W*",
    "x": "KP*",
    "y": "KWR*",
    "z": "STKPW*",
}

modifiers = {
    "acute": "-RP",
    "breve": "-FRBLG",
    "caron": "-FBL",
    "cedilla": "-RPB",
    "comma": "-B",
    "diaeresis": "-FL",
    "dotAbove": "-F",
    "dotBelow": "-R",
    "grave": "-FB",
    "hook": "-FRP",
    "horn": "-BLG",
    "macron": "-FP",
    "ogonek": "-PBG", # "little tail"
    "ring": "-FRPB",
    "stroke": "-RB",
    "slash": "-BL",
    "tilde": "-FPBG",

    "turned": "-FG",
    "inverted": "-RBG",
    "reversed": "-LG",
}

tbd = [
    {
        "name": "A with ogonek (Cyrillic)", # TODO
        "majuscule": ("A", "А̨"),
        "minuscule": ("a", "а̨"),
        "modifiers": ["ogonek"],
        "link": "https://en.wikipedia.org/wiki/A_with_ogonek_(Cyrillic)",
    },
    {,
        "name": "Y with double acute (Cyrillic)",
        "majuscule": ("Y", "Ӳ"),
        "minuscule": ("y", "ӳ"),
        "modifiers": ["acute", "acute"],
        "link": "https://en.wikipedia.org/wiki/Double_acute_accent#Letters_with_double_acute",
    },
    {
        "name": "Schwa with cedilla",
        "majuscule": ("E", "Ə̧"),
        "minuscule": ("e", "ə̧"),
        "modifiers": ["inverted", "cedilla"], # TODO
        "link": "https://en.wikipedia.org/wiki/Cedilla",
    },
    {
        "name": "Ɛ̧", # TODO
        "majuscule": ("E", "Ɛ̧"),
        "minuscule": ("e", "ɛ̧"),
        "modifiers": [], # TODO
        "link": "https://en.wikipedia.org/wiki/Cedilla",
    },
    {
        "name": "Reversed E",
        "majuscule": ("E", "Ǝ"),
        "minuscule": ("e", "ǝ"),
        "modifiers": ["reversed"],
        "link": "https://en.wikipedia.org/wiki/%C6%8E",
    },
    {
        "name": "Eth",
        "majuscule": ("D", "Ð"),
        "minuscule": ("d", "ð"),
        "modifiers": ["slash"],
        "link": "https://en.wikipedia.org/wiki/Eth",
    },
    {
        "name": "Voiced glottal fricative",
        "majuscule": ("H", "Ɦ"),
        "minuscule": ("h", "ɦ"),
        "modifiers": [], # TODO
        "link": "https://en.wikipedia.org/wiki/Voiced_glottal_fricative",
    },
    {
        "name": "Reversed C", # TODO
        "majuscule": ("C", "Ↄ"),
        "minuscule": ("c", "ↄ"),
        "modifiers": ["reversed"],
        "link": "https://en.wikipedia.org/wiki/Claudian_letters", # TODO
    },
    {
        "name": "Reversed C with cedilla",
        "majuscule": ("C", "Ɔ̧"),
        "minuscule": ("c", "ɔ̧"),
        "modifiers": ["reversed", "cedilla"],
        "link": "https://en.wikipedia.org/wiki/%C6%86%CC%A7",
    },
    {
        "name": "Turned F",
        "majuscule": ("F", "Ⅎ"),
        "minuscule": ("f", "ⅎ"),
        "modifiers": ["turned"],
        "link": "https://en.wikipedia.org/wiki/Claudian_letters", # TODO
    },
    {
        "name": "Ezh with caron",
        "majuscule": ("", "Ǯ"),
        "minuscule": ("", "ǯ"),
        "modifiers": ["caron"],
        "link": "https://en.wikipedia.org/wiki/%C7%AE",
    },
]

connectedDiacritics = [
    {
        "name": "A with ogonek",
        "majuscule": ("A", "Ą"),
        "minuscule": ("a", "ą"),
        "modifiers": ["ogonek"], #TODO
        "link": "https://en.wikipedia.org/wiki/%C4%84",
    },
    {
        "name": "A with cedilla",
        "majuscule": ("A", "Ą"),
        "minuscule": ("a", "Ą"),
        "modifiers": ["cedilla"],
        "link": "https://en.wikipedia.org/wiki/Cedilla",
    },
    {
        "name": "B with a hook",
        "majuscule": ("B", "Ɓ"),
        "minuscule": ("b", "ɓ"),
        "modifiers": ["hook"],
        "link": "https://en.wikipedia.org/wiki/%C6%81",
    },
    {
        "name": "C with hook",
        "majuscule": ("C", "Ƈ"),
        "minuscule": ("c", "ƈ"),
        "modifiers": ["hook"],
        "link": "https://en.wikipedia.org/wiki/%C6%87",
    },
    {
        "name": "C with cedilla",
        "majuscule": ("C", "Ç"),
        "minuscule": ("c", "ç"),
        "modifiers": ["cedilla"],
        "link": "https://en.wikipedia.org/wiki/%C3%87",
    },
    {
        "name": "D with stroke",
        "majuscule": ("D", "Đ"),
        "minuscule": ("d", "đ"),
        "modifiers": ["stroke"],
        "link": "https://en.wikipedia.org/wiki/D_with_stroke",
    },
    {
        "name": "D with hook",
        "majuscule": ("D", "Ɗ"),
        "minuscule": ("d", "ɗ"),
        "modifiers": ["hook"],
        "link": "https://en.wikipedia.org/wiki/%C6%8A",
    },
    {
        "name": "African D",
        "majuscule": ("D", "Ɖ"),
        "minuscule": ("d", "ɖ"),
        "modifiers": [], # TODO
        "link": "https://en.wikipedia.org/wiki/African_D",
    },
    {
        "name": "E with ogonek",
        "majuscule": ("E", "Ę"),
        "minuscule": ("e", "ę"),
        "modifiers": ["ogonek"],
        "link": "https://en.wikipedia.org/wiki/%C4%98",
    },
    {
        "name": "E with cedilla",
        "majuscule": ("E", "Ȩ"),
        "minuscule": ("e", "ȩ"),
        "modifiers": ["cedilla"],
        "link": "https://en.wikipedia.org/wiki/Cedilla",
    },
    {
        "name": "F with hook",
        "majuscule": ("F", "Ƒ"),
        "minuscule": ("f", "ƒ"),
        "modifiers": ["hook"],
        "link": "https://en.wikipedia.org/wiki/%C6%91",
    },
    {
        "name": "G with stroke",
        "majuscule": ("G", "Ǥ"),
        "minuscule": ("g", "ǥ"),
        "modifiers": ["stroke"],
        "link": "https://en.wikipedia.org/wiki/G_with_stroke",
    },
    {
        "name": "G with hook",
        "majuscule": ("G", "Ɠ"),
        "minuscule": ("g", "ɠ"),
        "modifiers": ["hook"],
        "link": "https://en.wikipedia.org/wiki/G_with_hook",
    },
    {
        "name": "H with stroke",
        "majuscule": ("H", "Ħ"),
        "minuscule": ("h", "ħ"),
        "modifiers": ["stroke"],
        "link": "https://en.wikipedia.org/wiki/H_with_stroke",
    },
    {
        "name": "I with ogonek",
        "majuscule": ("I", "Į"),
        "minuscule": ("i", "į"),
        "modifiers": ["ogonek"],
        "link": "https://en.wikipedia.org/wiki/%C4%AE",
    },
    {
        "name": "I with cedilla",
        "majuscule": ("I", "I̧"),
        "minuscule": ("i", "į"),
        "modifiers": ["cedilla"],
        "link": "https://en.wikipedia.org/wiki/Cedilla",
    },
    {
        "name": "I with bar",
        "majuscule": ("I", "Ɨ"),
        "minuscule": ("i", "ɨ"),
        "modifiers": ["stroke"],
        "link": "https://en.wikipedia.org/wiki/I_with_bar", # TODO
    },
    {
        "name": "Barred I with cedilla",
        "majuscule": ("I", "Ɨ̧"),
        "minuscule": ("i", "ɨ"),
        "modifiers": ["stroke", "cedilla"],
        "link": "https://en.wikipedia.org/wiki/Cedilla",
    },
    {
        "name": "K with hook",
        "majuscule": ("K", "Ƙ"),
        "minuscule": ("k", "ƙ"),
        "modifiers": ["hook"],
        "link": "https://en.wikipedia.org/wiki/%C6%98",
    },
    {
        "name": "L with stroke",
        "majuscule": ("L", "Ł"),
        "minuscule": ("l", "ł"),
        "modifiers": ["slash"], # TODO
        "link": "https://en.wikipedia.org/wiki/%C5%81",
    },
    {
        "name": "L with bar",
        "majuscule": ("L", "Ƚ"),
        "minuscule": ("l", "ƚ"),
        "modifiers": ["stroke"], # TODO
        "link": "https://en.wikipedia.org/wiki/L_with_bar",
    },
    {
        "name": "M with cedilla",
        "majuscule": ("M", "M̧"),
        "minuscule": ("m", "m̧"),
        "modifiers": ["cedilla"],
        "link": "https://en.wikipedia.org/wiki/Cedilla",
    },
    {
        "name": "palatal nasal", # TODO
        "majuscule": ("N", "Ɲ"),
        "minuscule": ("n", "ɲ"),
        "modifiers": [], # TODO
        "link": "https://en.wikipedia.org/wiki/%C6%9D",
    },
    {
        "name": "O with ogonek",
        "majuscule": ("Q", "Ǫ"),
        "minuscule": ("q", "ǫ"),
        "modifiers": ["ogonek"],
        "link": "https://en.wikipedia.org/wiki/%C7%AA",
    },
    {
        "name": "O with cedilla",
        "majuscule": ("O", "O̧"),
        "minuscule": ("o", "o̧"),
        "modifiers": ["cedilla"],
        "link": "https://en.wikipedia.org/wiki/Cedilla",
    },
    {
        "name": "O with stroke",
        "majuscule": ("O", "Ø"),
        "minuscule": ("o", "ø"),
        "modifiers": ["slash"],
        "link": "https://en.wikipedia.org/wiki/%C3%98",
    },
    {
        "name": "O with horn",
        "majuscule": ("O", "Ơ"),
        "minuscule": ("o", "ơ"),
        "modifiers": ["horn"],
        "link": "https://en.wikipedia.org/wiki/%C6%A0",
    },
    {
        "name": "P with hook",
        "majuscule": ("P", "Ƥ"),
        "minuscule": ("p", "ƥ"),
        "modifiers": ["hook"],
        "link": "https://en.wikipedia.org/wiki/%C6%A4",
    },
    {
        "name": "R with stroke",
        "majuscule": ("R", "Ɍ"),
        "minuscule": ("r", "ɍ"),
        "modifiers": ["stroke"],
        "link": "https://en.wikipedia.org/wiki/R_with_stroke",
    },
    {
        "name": "S with cedilla",
        "majuscule": ("S", "Ş"),
        "minuscule": ("s", "ş"),
        "modifiers": ["cedilla"],
        "link": "https://en.wikipedia.org/wiki/%C5%9E",
    },
    {
        "name": "T with hook",
        "majuscule": ("T", "Ƭ"),
        "minuscule": ("t", "ƭ"),
        "modifiers": ["hook"],
        "link": "https://en.wikipedia.org/wiki/%C6%AC",
    },
    {
        "name": "T with cedilla",
        "majuscule": ("T", "Ţ"),
        "minuscule": ("t", "ţ"),
        "modifiers": ["cedilla"],
        "link": "https://en.wikipedia.org/wiki/%C5%A2",
    },
    {
        "name": "T with stroke",
        "majuscule": ("T", "Ŧ"),
        "minuscule": ("t", "ŧ"),
        "modifiers": ["stroke"],
        "link": "https://en.wikipedia.org/wiki/T_with_stroke",
    },
    {
        "name": "U with ogonek",
        "majuscule": ("U", "Ų"),
        "minuscule": ("u", "ų"),
        "modifiers": ["ogonek"],
        "link": "https://en.wikipedia.org/wiki/%C5%B2",
    },
    {
        "name": "U with cedilla",
        "majuscule": ("U", "U̧"),
        "minuscule": ("u", "u̧"),
        "modifiers": ["cedilla"],
        "link": "https://en.wikipedia.org/wiki/Cedilla",
    },
    {
        "name": "U with horn",
        "majuscule": ("U", "Ư"),
        "minuscule": ("u", "ư"),
        "modifiers": ["horn"],
        "link": "https://en.wikipedia.org/wiki/%C6%AF",
    },
    {
        "name": "U with bar",
        "majuscule": ("U", "Ʉ"),
        "minuscule": ("u", "ʉ"),
        "modifiers": ["stroke"],
        "link": "https://en.wikipedia.org/wiki/U_with_bar",
    },
    {
        "name": "Y with ogonek",
        "majuscule": ("Y", "Y̨"),
        "minuscule": ("y", "y̨"),
        "modifiers": ["ogonek"],
        "link": "https://en.wikipedia.org/wiki/Ogonek",
    },
    {
        "name": "Y with hook",
        "majuscule": ("Y", "Ƴ"),
        "minuscule": ("y", "ƴ"),
        "modifiers": ["hook"],
        "link": "https://en.wikipedia.org/wiki/%C6%B3",
    },
]

detachedDiacritics = [
    {
        "name": "A with acute",
        "majuscule": ("A", "Á"),
        "minuscule": ("a", "á"),
        "modifiers": ["acute"],
        "link": "https://en.wikipedia.org/wiki/%C3%81",
    },
    {
        "name": "A with grave",
        "majuscule": ("A", "À"),
        "minuscule": ("a", "à"),
        "modifiers": ["grave"],
        "link": "https://en.wikipedia.org/wiki/%C3%80",
    },
    {
        "name": "A with dot above",
        "majuscule": ("A", "Ȧ"),
        "minuscule": ("a", "ȧ"),
        "modifiers": ["dotAbove"],
        "link": "https://en.wikipedia.org/wiki/%C8%A6",
    },
    {
        "name": "A with circumflex",
        "majuscule": ("A", "Â"),
        "minuscule": ("a", "â"),
        "modifiers": ["circumflex"],
        "link": "https://en.wikipedia.org/wiki/%C3%82",
    },
    {
        "name": "A with diaeresis",
        "majuscule": ("A", "Ä"),
        "minuscule": ("a", "ä"),
        "modifiers": ["diaeresis"],
        "link": "https://en.wikipedia.org/wiki/%C3%84",
    },
    {
        "name": "A with diaeresis and macron",
        "majuscule": ("A", "Ǟ"),
        "minuscule": ("a", "ǟ"),
        "modifiers": ["diaeresis", "macron"],
        "link": "https://en.wikipedia.org/wiki/Livonian_language#Alphabet",
    },
    {
        "name": "A with caron",
        "majuscule": ("A", "Â"),
        "minuscule": ("a", "ǎ"),
        "modifiers": ["caron"],
        "link": "https://en.wikipedia.org/wiki/Caron",
    },
    {
        "name": "A with breve",
        "majuscule": ("A", "Ă"),
        "minuscule": ("a", "ă"),
        "modifiers": ["breve"],
        "link": "https://en.wikipedia.org/wiki/%C4%82",
    },
    {
        "name": "A with macron",
        "majuscule": ("A", "Ā"),
        "minuscule": ("a", "ā"),
        "modifiers": ["macron"],
        "link": "https://en.wikipedia.org/wiki/%C4%80",
    },
    {
        "name": "A with tilde",
        "majuscule": ("A", "Ã"),
        "minuscule": ("a", "ã"),
        "modifiers": ["tilde"],
        "link": "https://en.wikipedia.org/wiki/%C3%83",
    },
    {
        "name": "A with ring above",
        "majuscule": ("A", "Å"),
        "minuscule": ("a", "å"),
        "modifiers": ["ring"],
        "link": "https://en.wikipedia.org/wiki/%C3%85",
    },
    {
        "name": "A with ring above and acute",
        "majuscule": ("A", "Ǻ"),
        "minuscule": ("a", "ǻ"),
        "modifiers": ["ring", "acute"],
        "link": "https://en.wikipedia.org/wiki/%C3%85#On_computers",
    },
    {,
        "name": "A with double acute",
        "majuscule": ("A", "A̋"),
        "minuscule": ("a", "a̋"),
        "modifiers": ["acute", "acute"],
        "link": "https://en.wikipedia.org/wiki/Double_acute_accent#Letters_with_double_acute",
    },
    {
        "name": "AE ligature with acute",
        "majuscule": ("Æ", "Ǽ"),
        "minuscule": ("æ", "ǽ"),
        "modifiers": ["acute"],
        "link": "https://en.wikipedia.org/wiki/%C3%86",
    },
    {
        "name": "AE ligature with macron",
        "majuscule": ("Æ", "Ǣ"),
        "minuscule": ("æ", "ǣ"),
        "modifiers": ["macron"],
        "link": "https://en.wikipedia.org/wiki/%C3%86",
    },
    {
        "name": "AE ligature with grave",
        "majuscule": ("Æ", "Æ̀"),
        "minuscule": ("æ", "æ̀"),
        "modifiers": ["grave"],
        "link": "https://en.wikipedia.org/wiki/%C3%86",
    },
    {
        "name": "AE ligature with circumflex",
        "majuscule": ("Æ", "Æ̂"),
        "minuscule": ("æ", "æ̂"),
        "modifiers": ["circumflex"],
        "link": "https://en.wikipedia.org/wiki/%C3%86",
    },
    {
        "name": "AE ligature with tilde",
        "majuscule": ("Æ", "Æ̃"),
        "minuscule": ("æ", "æ̃"),
        "modifiers": ["tilde"],
        "link": "https://en.wikipedia.org/wiki/%C3%86",
    },
    {
        "name": "B with dot below",
        "majuscule": ("B", "Ḅ"),
        "minuscule": ("b", "ḅ"),
        "modifiers": ["dotBelow"],
        "link": "https://en.wikipedia.org/wiki/Dot_(diacritic)",
    },
    {
        "name": "C with acute",
        "majuscule": ("C", "Ć"),
        "minuscule": ("c", "ć"),
        "modifiers": ["acute"],
        "link": "https://en.wikipedia.org/wiki/%C4%86",
    },
    {
        "name": "C with dot above",
        "majuscule": ("C", "Ċ"),
        "minuscule": ("c", "ċ"),
        "modifiers": ["dotAbove"],
        "link": "https://en.wikipedia.org/wiki/%C4%8A",
    },
    {
        "name": "C with circumflex",
        "majuscule": ("C", "Ĉ"),
        "minuscule": ("c", "ĉ"),
        "modifiers": ["circumflex"],
        "link": "https://en.wikipedia.org/wiki/%C4%88",
    },
    {
        "name": "C with caron",
        "majuscule": ("C", "Č"),
        "minuscule": ("c", "č"),
        "modifiers": ["caron"],
        "link": "https://en.wikipedia.org/wiki/%C4%8C",
    },
    {
        "name": "D with dot below",
        "majuscule": ("D", "Ḍ"),
        "minuscule": ("d", "ḍ"),
        "modifiers": ["dotBelow"],
        "link": "https://en.wikipedia.org/wiki/%E1%B8%8C",
    },
    {
        "name": "D with cedilla",
        "majuscule": ("D", "Ḑ"),
        "minuscule": ("d", "ḑ"),
        "modifiers": ["cedilla"],
        "link": "https://en.wikipedia.org/wiki/%E1%B8%90",
    },
    {
        "name": "D with circumflex",
        "majuscule": ("D", "Ḓ"),
        "minuscule": ("d", "ḑ"),
        "modifiers": ["circumflex"],
        "link": "https://en.wikipedia.org/wiki/Circumflex",
    },
    {
        "name": "E with acute",
        "majuscule": ("E", "É"),
        "minuscule": ("e", "é"),
        "modifiers": ["acute"],
        "link": "https://en.wikipedia.org/wiki/%C3%89",
    },
    {
        "name": "E with grave",
        "majuscule": ("E", "È"),
        "minuscule": ("e", "è"),
        "modifiers": ["grave"],
        "link": "https://en.wikipedia.org/wiki/%C3%88",
    },
    {
        "name": "E with dot above",
        "majuscule": ("E", "Ė"),
        "minuscule": ("e", "ė"),
        "modifiers": ["dotAbove"],
        "link": "https://en.wikipedia.org/wiki/%C4%96",
    },
    {
        "name": "E with circumflex",
        "majuscule": ("E", "Ê"),
        "minuscule": ("e", "ê"),
        "modifiers": ["circumflex"],
        "link": "https://en.wikipedia.org/wiki/%C3%8A",
    },
    {
        "name": "E with diaeresis",
        "majuscule": ("E", "Ë"),
        "minuscule": ("e", "ë"),
        "modifiers": ["diaeresis"],
        "link": "https://en.wikipedia.org/wiki/%C3%8B",
    },
    {
        "name": "E with caron",
        "majuscule": ("E", "Ě"),
        "minuscule": ("e", "ě"),
        "modifiers": ["caron"],
        "link": "https://en.wikipedia.org/wiki/%C4%9A",
    },
    {
        "name": "E with breve",
        "majuscule": ("E", "Ĕ"),
        "minuscule": ("e", "ĕ"),
        "modifiers": ["breve"],
        "link": "https://en.wikipedia.org/wiki/Breve#Letters_with_breve",
    },
    {
        "name": "E with macron",
        "majuscule": ("E", "Ē"),
        "minuscule": ("e", "ē"),
        "modifiers": ["macron"],
        "link": "https://en.wikipedia.org/wiki/Macron_(diacritic)",
    },
    {
        "name": "E with tilde",
        "majuscule": ("E", "Ẽ"),
        "minuscule": ("e", "ẽ"),
        "modifiers": ["tilde"],
        "link": "https://en.wikipedia.org/wiki/%E1%BA%BC",
    },
    {
        "name": "E with ring above",
        "majuscule": ("E", "E̊"),
        "minuscule": ("e", "e̊"),
        "modifiers": ["ring"],
        "link": "https://en.wikipedia.org/wiki/Ring_(diacritic)",
    },
    {
        "name": "E with dot below",
        "majuscule": ("E", "Ẹ"),
        "minuscule": ("e", "ẹ"),
        "modifiers": ["dotBelow"],
        "link": "https://en.wikipedia.org/wiki/Dot_(diacritic)",
    },
    {
        "name": "G with acute",
        "majuscule": ("G", "Ǵ"),
        "minuscule": ("g", "ǵ"),
        "modifiers": ["acute"],
        "link": "https://en.wikipedia.org/wiki/%C7%B4",
    },
    {
        "name": "G with dot above",
        "majuscule": ("G", "Ġ"),
        "minuscule": ("g", "ġ"),
        "modifiers": ["dotAbove"],
        "link": "https://en.wikipedia.org/wiki/%C4%A0",
    },
    {
        "name": "G with circumflex",
        "majuscule": ("G", "Ĝ"),
        "minuscule": ("g", "ĝ"),
        "modifiers": ["circumflex"],
        "link": "https://en.wikipedia.org/wiki/%C4%9C",
    },
    {
        "name": "G with caron",
        "majuscule": ("G", "Ǧ"),
        "minuscule": ("g", "ǧ"),
        "modifiers": ["caron"],
        "link": "https://en.wikipedia.org/wiki/%C7%A6",
    },
    {
        "name": "G with breve",
        "majuscule": ("G", "Ğ"),
        "minuscule": ("g", "ğ"),
        "modifiers": ["breve"],
        "link": "https://en.wikipedia.org/wiki/%C4%9E",
    },
    {
        "name": "G with tilde",
        "majuscule": ("G", "G̃"),
        "minuscule": ("g", "g̃"),
        "modifiers": ["tilde"],
        "link": "https://en.wikipedia.org/wiki/G%CC%83",
    },
    {
        "name": "G with cedilla",
        "majuscule": ("G", "Ģ"),
        "minuscule": ("g", "ģ"),
        "modifiers": ["cedilla"],
        "link": "https://en.wikipedia.org/wiki/%C4%A2",
    },
    {
        "name": "H with circumflex",
        "majuscule": ("H", "Ĥ"),
        "minuscule": ("h", "ĥ"),
        "modifiers": ["circumflex"],
        "link": "https://en.wikipedia.org/wiki/%C4%A4",
    },
    {
        "name": "H with dot below",
        "majuscule": ("H", "Ḥ"),
        "minuscule": ("h", "ĥ"),
        "modifiers": ["dotBelow"],
        "link": "https://en.wikipedia.org/wiki/Dot_(diacritic)",
    },
    {
        "name": "I with acute",
        "majuscule": ("I", "Í"),
        "minuscule": ("i", "í"),
        "modifiers": ["acute"],
        "link": "https://en.wikipedia.org/wiki/%C3%8D",
    },
    {
        "name": "I with grave",
        "majuscule": ("I", "Ì"),
        "minuscule": ("i", "ì"),
        "modifiers": ["grave"],
        "link": "https://en.wikipedia.org/wiki/%C3%8C",
    },
    {
        "name": "I with dot above",
        "majuscule": ("I", "İ"),
        "minuscule": ("i", "i"),
        "modifiers": ["dotAbove"],
        "link": "https://en.wikipedia.org/wiki/%C4%B0",
    },
    {
        "name": "I with circumflex",
        "majuscule": ("I", "Î"),
        "minuscule": ("i", "î"),
        "modifiers": ["circumflex"],
        "link": "https://en.wikipedia.org/wiki/%C3%8E",
    },
    {
        "name": "I with diaeresis",
        "majuscule": ("I", "Ï"),
        "minuscule": ("i", "ï"),
        "modifiers": ["diaeresis"],
        "link": "https://en.wikipedia.org/wiki/%C3%8F",
    },
    {
        "name": "I with caron",
        "majuscule": ("I", "Ǐ"),
        "minuscule": ("i", "ǐ"),
        "modifiers": ["caron"],
        "link": "https://en.wikipedia.org/wiki/Caron",
    },
    {
        "name": "I with breve",
        "majuscule": ("I", "Ĭ"),
        "minuscule": ("i", "ĭ"),
        "modifiers": ["breve"],
        "link": "https://en.wikipedia.org/wiki/Breve",
    },
    {
        "name": "I with macron",
        "majuscule": ("I", "Ī"),
        "minuscule": ("i", "ī"),
        "modifiers": ["macron"],
        "link": "https://en.wikipedia.org/wiki/Macron_(diacritic)",
    },
    {
        "name": "I with tilde",
        "majuscule": ("I", "Ĩ"),
        "minuscule": ("i", "ĩ"),
        "modifiers": ["tilde"],
        "link": "https://en.wikipedia.org/wiki/Tilde",
    },
    {
        "name": "I with dot below",
        "majuscule": ("I", "Ị"),
        "minuscule": ("i", "ị"),
        "modifiers": ["dotBelow"],
        "link": "https://en.wikipedia.org/wiki/Dot_(diacritic)",
    },
    {
        "name": "J with circumflex",
        "majuscule": ("J", "Ĵ"),
        "minuscule": ("j", "ĵ"),
        "modifiers": ["circumflex"],
        "link": "https://en.wikipedia.org/wiki/%C4%B4",
    },
    {
        "name": "K with cedilla",
        "majuscule": ("K", "Ķ"),
        "minuscule": ("k", "ķ"),
        "modifiers" ["cedilla"],
        "link": "https://en.wikipedia.org/wiki/%C4%B6",
    },
    {
        "name": "K with caron",
        "majuscule": ("K", "Ǩ"),
        "minuscule": ("k", "ǩ"),
        "modifiers": ["caron"],
        "link": "https://en.wikipedia.org/wiki/%C7%A8",
    },
    {
        "name": "L with acute",
        "majuscule": ("L", "Ĺ"),
        "minuscule": ("l", "ĺ"),
        "modifiers": ["acute"],
        "link": "https://en.wikipedia.org/wiki/Acute_accent",
    },
    {
        "name": "L with cedilla",
        "majuscule": ("L", "Ļ"),
        "minuscule": ("l", "ļ"),
        "modifiers": ["cedilla"],
        "link": "https://en.wikipedia.org/wiki/Cedilla",
    },
    {
        "name": "L with caron",
        "majuscule": ("L", "Ľ"),
        "minuscule": ("l", "ľ"),
        "modifiers": ["caron"],
        "link": "https://en.wikipedia.org/wiki/%C4%BD",
    },
    {
        "name": "L with interpunct",
        "majuscule": ("L", "Ŀ"),
        "minuscule": ("l", "ŀ"),
        "modifiers": ["interpunct"],
        "link": "https://en.wikipedia.org/wiki/Interpunct#Catalan",
    },
    {
        "name": "L with dot below",
        "majuscule": ("L", "Ḷ"),
        "minuscule": ("l", "ḷ"),
        "modifiers": ["dotBelow"],
        "link": "https://en.wikipedia.org/wiki/%E1%B8%B6",
    },
    {
        "name": "L with circumflex",
        "majuscule": ("L", "Ḽ"),
        "minuscule": ("l", "ḽ"),
        "modifiers": ["circumflex"],
        "link": "https://en.wikipedia.org/wiki/Circumflex",
    },
    {
        "name": "M with circumflex",
        "majuscule": ("M", "M̂"),
        "minuscule": ("m", "m̂"),
        "modifiers": ["circumflex"],
        "link": "https://en.wikipedia.org/wiki/Circumflex",
    },
    {
        "name": "M with macron",
        "majuscule": ("M", "M̄"),
        "minuscule": ("m", "m̄"),
        "modifiers": ["macron"],
        "link": "https://en.wikipedia.org/wiki/Macron_(diacritic)",
    },
    {
        "name": "N with acute",
        "majuscule": ("N", "Ń"),
        "minuscule": ("n", "ń"),
        "modifiers": ["acute"],
        "link": "https://en.wikipedia.org/wiki/%C5%83",
    },
    {
        "name": "N with circumflex",
        "majuscule": ("N", "N̂"),
        "minuscule": ("n", "n̂"),
        "modifiers": ["circumflex"],
        "link": "https://en.wikipedia.org/wiki/Circumflex",
    },
    {
        "name": "N with dot above",
        "majuscule": ("N", "Ṅ"),
        "minuscule": ("n", "ṅ"),
        "modifiers": ["dotAbove"],
        "link": "https://en.wikipedia.org/wiki/%E1%B9%84",
    },
    {
        "name": "N with diaeresis",
        "majuscule": ("N", "N̈"),
        "minuscule": ("n", "n̈"),
        "modifiers": ["diaeresis"],
        "link": "https://en.wikipedia.org/wiki/N%CC%88",
    },
    {
        "name": "N with caron",
        "majuscule": ("N", "Ň"),
        "minuscule": ("n", "ň"),
        "modifiers": ["caron"],
        "link": "https://en.wikipedia.org/wiki/%C5%87",
    },
    {
        "name": "N with macron",
        "majuscule": ("N", "N̄"),
        "minuscule": ("n", "n̄"),
        "modifiers": ["macron"],
        "link": "https://en.wikipedia.org/wiki/Macron_(diacritic)",
    },
    {
        "name": "N with tilde",
        "majuscule": ("N", "Ñ"),
        "minuscule": ("n", "ñ"),
        "modifiers": ["tilde"],
        "link": "https://en.wikipedia.org/wiki/%C3%91",
    },
    {
        "name": "N with cedilla",
        "majuscule": ("N", "Ņ"),
        "minuscule": ("n", "ņ"),
        "modifiers": ["cedilla"],
        "link": "https://en.wikipedia.org/wiki/Cedilla",
    },
    {
        "name": "N with circumflex",
        "majuscule": ("N", "Ṋ"),
        "minuscule": ("n", "ṋ"),
        "modifiers": ["circumflex"],
        "link": "https://en.wikipedia.org/wiki/Circumflex",
    },
    {
        "name": "O with acute",
        "majuscule": ("O", "Ó"),
        "minuscule": ("o", "ó"),
        "modifiers": ["acute"],
        "link": "https://en.wikipedia.org/wiki/%C3%93",
    },
    {
        "name": "O with grave",
        "majuscule": ("O", "Ò"),
        "minuscule": ("o", "ò"),
        "modifiers": ["grave"],
        "link": "https://en.wikipedia.org/wiki/%C3%92",
    },
    {
        "name": "O with dot above",
        "majuscule": ("O", "Ȯ"),
        "minuscule": ("o", "ȯ"),
        "modifiers": ["dotAbove"],
        "link": "https://en.wikipedia.org/wiki/Dot_(diacritic)",
    },
    {
        "name": "O with dot above and macron",
        "majuscule": ("O", "Ȱ"),
        "minuscule": ("o", "ȱ"),
        "modifiers": ["dotAbove", "macron"],
        "link": "https://en.wikipedia.org/wiki/Dot_(diacritic)",
    },
    {
        "name": "O with circumflex",
        "majuscule": ("O", "Ô"),
        "minuscule": ("o", "ô"),
        "modifiers": ["circumflex"],
        "link": "https://en.wikipedia.org/wiki/Circumflex",
    },
    {
        "name": "O with diaeresis",
        "majuscule": ("O", "Ö"),
        "minuscule": ("o", "ö"),
        "modifiers": ["diaeresis"],
        "link": "https://en.wikipedia.org/wiki/%C3%96",
    },
    {
        "name": "O with diaeresis and macron",
        "majuscule": ("O", "Ȫ"),
        "minuscule": ("o", "ȫ"),
        "modifiers": ["diaeresis", "macron"],
        "link": "https://en.wikipedia.org/wiki/%C3%96",
    },
    {
        "name": "O with caron",
        "majuscule": ("O", "Ǒ"),
        "minuscule": ("o", "ǒ"),
        "modifiers": ["caron"],
        "link": "https://en.wikipedia.org/wiki/Caron",
    },
    {
        "name": "O with breve",
        "majuscule": ("O", "Ŏ"),
        "minuscule": ("o", "ŏ"),
        "modifiers": ["breve"],
        "link": "https://en.wikipedia.org/wiki/Breve",
    },
    {
        "name": "O with macron",
        "majuscule": ("O", "Ō"),
        "minuscule": ("o", "ō"),
        "modifiers": ["macron"],
        "link": "https://en.wikipedia.org/wiki/Macron_(diacritic)",
    },
    {
        "name": "O with tilde",
        "majuscule": ("O", "Õ"),
        "minuscule": ("o", "õ"),
        "modifiers": ["tilde"],
        "link": "https://en.wikipedia.org/wiki/%C3%95"
    },
    {
        "name": "O with tilde and macron",
        "majuscule": ("O", "Ȭ"),
        "minuscule": ("o", "ȭ"),
        "modifiers": ["tilde", "macron"],
        "link": "https://en.wikipedia.org/wiki/Livonian_language#Alphabet",
    },
    {
        "name": "O with double acute",
        "majuscule": ("O", "Ő"),
        "minuscule": ("o", "ő"),
        "modifiers": ["acute", "acute"],
        "link": "https://en.wikipedia.org/wiki/%C5%90",
    },
    {
        "name": "O with dot below",
        "majuscule": ("O", "Ọ"),
        "minuscule": ("o", "ọ"),
        "modifiers": ["dotBelow"],
        "link": "https://en.wikipedia.org/wiki/Dot_(diacritic)",
    },
    {
        "name": "O with slash and acute",
        "majuscule": ("O", "Ǿ"),
        "minuscule": ("o", "ǿ"),
        "modifiers": ["slash", "acute"],
        "link": "https://en.wikipedia.org/wiki/%C3%98#%C7%BE",
    },
    {
        "name": "O with horn",
        "majuscule": ("O", "Ơ"),
        "minuscule": ("o", "ơ"),
        "modifiers": ["horn"],
        "link": "https://en.wikipedia.org/wiki/%C6%A0",
    },
    {
        "name": "P with macron ",
        "majuscule": ("P", "P̄"),
        "minuscule": ("p", "p̄"),
        "modifiers": ["macron"],
        "link": "https://en.wikipedia.org/wiki/Macron_(diacritic)#Letter_extension",
    },
    {
        "name": "R with acute",
        "majuscule": ("R", "Ŕ"),
        "minuscule": ("r", "ŕ"),
        "modifiers": ["acute"],
        "link": "https://en.wikipedia.org/wiki/%C5%94",
    },
    {
        "name": "R with caron",
        "majuscule": ("R", "Ř"),
        "minuscule": ("r", "ř"),
        "modifiers": ["caron"],
        "link": "https://en.wikipedia.org/wiki/%C5%98",
    },
    {
        "name": "R with cedilla",
        "majuscule": ("R", "Ŗ"),
        "minuscule": ("r", "ŗ"),
        "modifiers": ["cedilla"],
        "link": "https://en.wikipedia.org/wiki/Cedilla",
    },
    {
        "name": "R with dot below",
        "majuscule": ("R", "Ṛ"),
        "minuscule": ("r", "ṛ"),
        "modifiers": ["dotBelow"],
        "link": "https://en.wikipedia.org/wiki/%E1%B9%9A",
    },
    {
        "name": "S with acute",
        "majuscule": ("S", "Ś"),
        "minuscule": ("s", "ś"),
        "modifiers": ["acute"],
        "link": "https://en.wikipedia.org/wiki/%C5%9A",
    },
    {
        "name": "S with caron",
        "majuscule": ("S", "Ŝ"),
        "minuscule": ("s", "ŝ"),
        "modifiers": ["caron"],
        "link": "https://en.wikipedia.org/wiki/%C5%9C",
    },
    {
        "name": "S with dot above",
        "majuscule": ("S", "Ṡ"),
        "minuscule": ("s", "ṡ"), # TODO ẛ
        "modifiers": ["dotAbove"],
        "link": "https://en.wikipedia.org/wiki/%E1%B9%A0",
    },
    {
        "name": "S with caron",
        "majuscule": ("S", "Š"),
        "minuscule": ("s", "š"),
        "modifiers": ["caron"],
        "link": "https://en.wikipedia.org/wiki/%C5%A0",
    },
    {
        "name": "S with comma below",
        "majuscule": ("S", "Ș"),
        "minuscule": ("s", "ș"),
        "modifiers": ["comma"],
        "link": "https://en.wikipedia.org/wiki/%C8%98",
    },
    {
        "name": "S with dot below",
        "majuscule": ("S", "Ș"),
        "minuscule": ("s", "ș"),
        "modifiers": ["dotBelow"],
        "link": "https://en.wikipedia.org/wiki/%E1%B9%A2",
    },
    {
        "name": "T with caron",
        "majuscule": ("T", "Ť"),
        "minuscule": ("t", "ť"),
        "modifiers": ["caron"],
        "link": "https://en.wikipedia.org/wiki/%C5%A4",
    },
    {
        "name": "T with comma",
        "majuscule": ("T", "Ț"),
        "minuscule": ("t", "ț"),
        "modifiers": ["comma"],
        "link": "https://en.wikipedia.org/wiki/%C8%9A",
    },
    {
        "name": "T with dot below",
        "majuscule": ("T", "Ṭ"),
        "minuscule": ("t", "ṭ"),
        "modifiers": ["dotBelow"],
        "link": "https://en.wikipedia.org/wiki/%E1%B9%AC",
    },
    {
        "name": "T with circumflex",
        "majuscule": ("T", "Ṱ"),
        "minuscule": ("t", "ṱ"),
        "modifiers": ["circumflex"],
        "link": "https://en.wikipedia.org/wiki/Circumflex",
    },
    {
        "name": "U with acute",
        "majuscule": ("U", "Ú"),
        "minuscule": ("u", "ú"),
        "modifiers": ["acute"],
        "link": "https://en.wikipedia.org/wiki/%C3%9A",
    },
    {
        "name": "U with grave",
        "majuscule": ("U", "Ù"),
        "minuscule": ("u", "ù"),
        "modifiers": ["grave"],
        "link": "https://en.wikipedia.org/wiki/Grave_accent",
    },
    {
        "name": "U with circumflex",
        "majuscule": ("U", "Û"),
        "minuscule": ("u", "û"),
        "modifiers": ["circumflex"],
        "link": "https://en.wikipedia.org/wiki/%C3%9B",
    },
    {
        "name": "U with diaeresis",
        "majuscule": ("U", "Ü"),
        "minuscule": ("u", "ü"),
        "modifiers": ["diaeresis"],
        "link": "https://en.wikipedia.org/wiki/%C3%9C",
    },
    {
        "name": "U with caron",
        "majuscule": ("U", "Ǔ"),
        "minuscule": ("u", "ǔ"),
        "modifiers": ["caron"],
        "link": "https://en.wikipedia.org/wiki/Caron",
    },
    {
        "name": "U with breve",
        "majuscule": ("U", "Ŭ"),
        "minuscule": ("u", "ŭ"),
        "modifiers": ["breve"],
        "link": "https://en.wikipedia.org/wiki/%C5%AC",
    },
    {
        "name": "U with macron",
        "majuscule": ("U", "Ū"),
        "minuscule": ("u", "ū"),
        "modifiers": ["macron"],
        "link": "https://en.wikipedia.org/wiki/Macron_(diacritic)",
    },
    {
        "name": "U with tilde",
        "majuscule": ("U", "Ũ"),
        "minuscule": ("u", "ũ"),
        "modifiers": ["tilde"],
        "link": "https://en.wikipedia.org/wiki/Tilde",
    },
    {
        "name": "U with double acute",
        "majuscule": ("U", "Ű"),
        "minuscule": ("u", "ű"),
        "modifiers": ["acute", "acute"],
        "link": "https://en.wikipedia.org/wiki/Double_acute_accent#Letters_with_double_acute",
    },
    {
        "name": "U with ring above",
        "majuscule": ("U", "Ů"),
        "minuscule": ("u", "ů"),
        "modifiers": ["ring"],
        "link": "https://en.wikipedia.org/wiki/Ring_(diacritic)",
    },
    {
        "name": "U with dot below",
        "majuscule": ("U", "Ụ"),
        "minuscule": ("u", "ụ"),
        "modifiers": ["dotBelow"],
        "link": "https://en.wikipedia.org/wiki/Dot_(diacritic)",
    },
    {
        "name": "W with acute",
        "majuscule": ("W", "Ẃ"),
        "minuscule": ("w", "ẃ"),
        "modifiers": ["acute"],
        "link": "https://en.wikipedia.org/wiki/%E1%BA%82",
    },
    {
        "name": "W with grave",
        "majuscule": ("W", "Ẁ"),
        "minuscule": ("w", "ẃ"),
        "modifiers": ["grave"],
        "link": "https://en.wikipedia.org/wiki/Grave_accent",
    },
    {
        "name": "W with circumflex",
        "majuscule": ("W", "Ŵ"),
        "minuscule": ("w", "ŵ"),
        "modifiers": ["circumflex"],
        "link": "https://en.wikipedia.org/wiki/Circumflex",
    },
    {
        "name": "W with diaeresis",
        "majuscule": ("W", "Ẅ"),
        "minuscule": ("w", "ẅ"),
        "modifiers": ["diaeresis"],
        "link": "https://en.wikipedia.org/wiki/Two_dots_(diacritic)",
    },
    {
        "name": "X with dot above",
        "majuscule": ("X", "Ẋ"),
        "minuscule": ("x", "ẋ"),
        "modifiers": ["dotAbove"],
        "link": "https://en.wikipedia.org/wiki/%E1%BA%8A",
    },
    {
        "name": "Y with acute",
        "majuscule": ("Y", "Ý"),
        "minuscule": ("y", "ý"),
        "modifiers": ["acute"],
        "link": "https://en.wikipedia.org/wiki/%C3%9D",
    },
    {
        "name": "Y with grave",
        "majuscule": ("Y", "Ỳ"),
        "minuscule": ("y", "ỳ"),
        "modifiers": ["grave"],
        "link": "https://en.wikipedia.org/wiki/Grave_accent",
    },
    {
        "name": "Y with circumflex",
        "majuscule": ("Y", "Ŷ"),
        "minuscule": ("y", "ŷ"),
        "modifiers": ["circumflex"],
        "link": "https://en.wikipedia.org/wiki/Circumflex",
    },
    {
        "name": "Y with diaeresis",
        "majuscule": ("Y", "Ÿ"),
        "minuscule": ("y", "ÿ"),
        "modifiers": ["diaeresis"],
        "link": "https://en.wikipedia.org/wiki/%C5%B8",
    },
    {
        "name": "Y with macron",
        "majuscule": ("Y", "Ȳ"),
        "minuscule": ("y", "ȳ"),
        "modifiers": ["macron"],
        "link": "https://en.wikipedia.org/wiki/%C8%B2",
    },
    {
        "name": "Y with tilde",
        "majuscule": ("Y", "Ỹ"),
        "minuscule": ("y", "ỹ"),
        "modifiers": ["tilde"],
        "link": "https://en.wikipedia.org/wiki/Tilde",
    },
    {
        "name": "Z with acute",
        "majuscule": ("Z", "Ź"),
        "minuscule": ("z", "ź"),
        "modifiers": ["acute"],
        "link": "https://en.wikipedia.org/wiki/%C5%B9",
    },
    {
        "name": "Z with dot above",
        "majuscule": ("Z", "Ż"),
        "minuscule": ("z", "ż"),
        "modifiers": ["dotAbove"],
        "link": "https://en.wikipedia.org/wiki/%C5%BB",
    },
    {
        "name": "Z with caron",
        "majuscule": ("Z", "Ž"),
        "minuscule": ("z", "ž"),
        "modifiers": ["caron"],
        "link": "https://en.wikipedia.org/wiki/%C5%BD",
    },
    {
        "name": "Z with dot below",
        "majuscule": ("Z", "Ẓ"),
        "minuscule": ("z", "ẓ"),
        "modifiers": ["dotBelow"],
        "link": "https://en.wikipedia.org/wiki/%E1%BA%92",
    },
]

