import json

latinAlphabet = {
    "A": "A*P",
    "a": "A*",
    "B": "PW*P",
    "b": "PW*",
    "C": "KR*P",
    "c": "KR*",
    "D": "TK*P",
    "d": "TK*",
    "E": "*EP",
    "e": "*E",
    "F": "TP*P",
    "f": "TP*",
    "G": "TKPW*P",
    "g": "TKPW*",
    "H": "H*P",
    "h": "H*",
    "I": "*EUP",
    "i": "*EU",
    "J": "SKWR*P",
    "j": "SKWR*",
    "K": "K*P",
    "k": "K*",
    "L": "HR*P",
    "l": "HR*",
    "M": "PH*P",
    "m": "PH*",
    "N": "TPH*P",
    "n": "TPH*",
    "O": "O*P",
    "o": "O*",
    "P": "P*P",
    "p": "P*",
    "Q": "KW*P",
    "q": "KW*",
    "R": "R*P",
    "r": "R*",
    "S": "S*P",
    "s": "S*",
    "T": "T*P",
    "t": "T*",
    "U": "*UP",
    "u": "*U",
    "V": "SR*P",
    "v": "SR*",
    "W": "W*P",
    "w": "W*",
    "X": "KP*P",
    "x": "KP*",
    "Y": "KWR*P",
    "y": "KWR*",
    "Z": "STKPW*P",
    "z": "STKPW*",
}

# these string pairs are used to wrap output characters to enforce case
lowerWraps = ("{>}{&", "}")
upperWraps = ("{-|}{&", "}")

# This the all the modifiers, and info for and about each one.
# Modifiers include diacritics, ligatures, rotations, and so on.
modifiers = {
    "acute": {
        "outline": "-RP",
        "name": "Acute",
        "docs": "Shaped like the acute symbol.",
    },
    "acuteDoubled": {
        "outline": "ERP",
        "name": "Double Acute",
        "docs": "The acute modifier shape, with the '[extra](#modifier-tweaks)' tweak.",
    },
    "breve": {
        "outline": "-FRBLG",
        "name": "Breve",
        "docs": "Shaped like the breve symbol.",
    },
    "breveBelow": {
        "outline": "UFRBLG",
        "name": "Breve Below",
        "docs": "The breve modifier shape, with the '[under](#modifier-tweaks)' tweak.",
    },
    "breveInverted": {
        "outline": "-FRPLG",
        "name": "Breve Inverted",
        "docs": "Shaped like the inverted breve symbol.",
    },
    "caron": {
        "outline": "-FBL",
        "name": "Caron",
        "docs": "Shaped like the caron symbol.",
    },
    "cedilla": {
        "outline": "-RPB",
        "name": "Cedilla",
        "docs": "Shaped like the cedilla, which hangs below the character, and curves to the left.",
    },
    "circumflex": {
        "outline": "-RPG",
        "name": "Circumflex",
        "docs": "Shaped like the circumflex symbol.",
    },
    "circumflexBelow": {
        "outline": "URPG",
        "name": "Circumflex Below",
        "docs": "The circumflex modifier shape, with the '[under](#modifier-tweaks)' tweak.",
    },
    "commaBelow": {
        "outline": "-B",
        "name": "Comma Below",
        "docs": "Chosen to mirror the shape used for the comma in the [Emily's Symbols](https://github.com/EPLHREU/emily-symbols) plugin.",
    },
    "diaeresis": {
        "outline": "-FL",
        "name": "Diaeresis/Umlaut",
        "docs": "Shaped like the diaeresis/umlaut symbols.<BR><BR>NOTE: [diaeresis](https://en.wikipedia.org/wiki/Diaeresis_(diacritic)) and [umlaut](https://en.wikipedia.org/wiki/Umlaut_(diacritic)) are distinct concepts, with separate uses, but are represented by the same Unicode code points. They are created via the same outline in this spelling system.",
    },
    "diaeresisBelow": {
        "outline": "-RG",
        "name": "Diaeresis Below",
        "docs": "The diaeresis/umlaut shape, but lower.",
    },
    "dotAbove": {
        "outline": "-F",
        "name": "Dot Above",
        "docs": "A single key, up high, like a dot above. See dot below.",
    },
    "dotBelow": {
        "outline": "-R",
        "name": "Dot Below",
        "docs": "Chosen to mirror the shape used for the period in the [Emily's Symbols](https://github.com/EPLHREU/emily-symbols) plugin. A single key, down low, like a dot below. See dot above.",
    },
    "grave": {
        "outline": "-FB",
        "name": "Grave",
        "docs": "Shaped like the grave symbol.",
    },
    "graveDoubled": {
        "outline": "EFB",
        "name": "Double Grave",
        "docs": "The grave modifier shape, with the '[extra](#modifier-tweaks)' tweak.",
    },
    "hookAbove": {
        "outline": "-FPB",
        "name": "Hook Above",
        "docs": "Shaped like the hook above symbol, sticking up, and curling to the left.",
    },
    "hook": {
        "outline": "-FRP",
        "name": "Hook",
        "docs": "Distinct from 'hook above', which is a detached diacritic, this is for characters with an attached hook. The hook shape was chosen to match most of these characters, which either curl up, then to the right, or to the left, then down, which makes the same curve. Imagine the chord shape attaching to some at the −R, and others at the −P. Some of the visual nature of this is down to fonts and rendering, of course, and a few letters don't match up well to this chord shape, and will just have to be memorized as exceptions for now.",
    },
    "horn": {
        "outline": "-BLG",
        "name": "Horn",
        "docs": "Shaped like the horn symbol, sticking out to the right and curving upward. The shape is also on the right-hand side of the modifier keys cluster, as the horn sticks out the right side of its characters.",
    },
    "interpunct": {
        "outline": "-FR",
        "name": "Interpunct",
        "docs": "An odd one, which joins the dot above and dot below characters. Think of it as the midpoint of the above and below dots, made by stroking both together.",
    },
    "lineBelow": {
        "outline": "UFP",
        "name": "Line Below",
        "docs": "When decomposed into base character + diacritic, the combining character for this set of Unicode composed characters is the macron below. Rather than use the the lower version of the chord, on the bottom row, this uses the '[under](#modifier-tweaks)' tweak with the macron shape, to respect this relation.",
    },
    "macron": {
        "outline": "-FP",
        "name": "Macron",
        "docs": "Shaped like the macron symbol.",
    },
    "ogonek": {
        "outline": "-PBG", # "little tail"
        "name": "Ogonek",
        "docs": "The ogonek, meaning 'little tail' in Polish, hangs off the bottom of its character, curling down and to the right.",
    },
    "ringAbove": {
        "outline": "-FRPB",
        "name": "Ring Above",
        "docs": "Think of this square of keys like a little circle, or ring.",
    },
    "ringBelow": {
        "outline": "UFRPB",
        "name": "Ring Below",
        "docs": "The ring above modifier shape, with the '[under](#modifier-tweaks)' tweak.",
    },
    "stroke": {
        "outline": "-RB",
        "name": "Stroke",
        "docs": "Like the macron, but lower, because it cuts through the character, rather than flying above it.",
    },
    "slash": {
        "outline": "-BL",
        "name": "Slash",
        "docs": "Like the acute, but shifted, to indicate that it's lower, and cuts through the character. A bit of a stretch, as it's shifted to the right, not down, but other options were used up. Maybe think of it like moving to the right while reading this text, which eventually wraps, and takes you down a line.",
    },
    "tilde": {
        "outline": "-FPBG",
        "name": "Tilde",
        "docs": "Shaped like the tilde symbol.",
    },
    "tildeBelow": {
        "outline": "UFPBG",
        "name": "Tilde Below",
        "docs": "The tilde modifier shape, with the '[under](#modifier-tweaks)' tweak.",
    },
    "ligature": {
        "outline": "-FRLG",
        "name": "Ligature",
        "docs": "[Ligatures](https://en.wikipedia.org/wiki/Ligature_(writing)) are two or more graphemes joined together, as in Æ. To output an existing ligature, stroke the two letters in left-to-right order, then stroke this modifier to merge them. Think of the two vertical columns as the two graphemes being joined. For characters that modify ligatures, like the AE ligature with circumflex, or the AE ligature turned, create the ligature first, before modifying it further."
    },
    "turned": {
        "outline": "-RL",
        "name": "Turned/Rotated",
        "docs": "This modifier allows access to characters that are turned, or rotated.",
    },
    "reversed": {
        "outline": "EURL",
        "name": "Reversed",
        "docs": "The turned modifier shape, with the '[inverted](#modifier-tweaks)' tweak.<BR><BR>This allows access to characters that are flipped, inverted, or reversed.",
    },
}

tbd = [
    {
        "name": "A with ogonek (Cyrillic)", # TODO
        "majuscule": ("A", "А̨"),
        "minuscule": ("a", "а̨"),
        "modifiers": ["ogonek"],
        "link": "https://en.wikipedia.org/wiki/A_with_ogonek_(Cyrillic)",
    },
    {
        "name": "Ɛ̧", # TODO
        "majuscule": ("E", "Ɛ̧"),
        "minuscule": ("e", "ɛ̧"),
        "modifiers": [], # TODO
        "link": "https://en.wikipedia.org/wiki/Cedilla",
    },
    {
        "name": "Reversed E",
        "majuscule": ("E", "Ǝ"),
        "minuscule": ("e", "ǝ"),
        "modifiers": ["reversed"],
        "link": "https://en.wikipedia.org/wiki/%C6%8E",
    },
    {
        "name": "Eth",
        "majuscule": ("D", "Ð"),
        "minuscule": ("d", "ð"),
        "modifiers": ["slash"],
        "link": "https://en.wikipedia.org/wiki/Eth",
    },
    {
        "name": "Voiced glottal fricative",
        "majuscule": ("H", "Ɦ"),
        "minuscule": ("h", "ɦ"),
        "modifiers": [], # TODO
        "link": "https://en.wikipedia.org/wiki/Voiced_glottal_fricative",
    },
    {
        "name": "Ezh with caron",
        "majuscule": ("", "Ǯ"),
        "minuscule": ("", "ǯ"),
        "modifiers": ["caron"],
        "link": "https://en.wikipedia.org/wiki/%C7%AE",
    },
    {
        "name": "African D",
        "majuscule": ("D", "Ɖ"),
        "minuscule": ("d", "ɖ"),
        "modifiers": [], # TODO
        "link": "https://en.wikipedia.org/wiki/African_D",
    },
    {
        "name": "palatal nasal", # TODO
        "majuscule": ("N", "Ɲ"),
        "minuscule": ("n", "ɲ"),
        "modifiers": [], # TODO
        "link": "https://en.wikipedia.org/wiki/%C6%9D",
    },
]

entries = [
    #  _ _             _
    # | (_) __ _  __ _| |_ _   _ _ __ ___  ___
    # | | |/ _` |/ _` | __| | | | '__/ _ \/ __|
    # | | | (_| | (_| | |_| |_| | | |  __/\__ \
    # |_|_|\__, |\__,_|\__|\__,_|_|  \___||___/
    #      |___/
    {
        "name": "AA ligature",
        "majuscule": ("AA", "Ꜳ"),
        "minuscule": ("aa", "ꜳ"),
        "modifiers": ["ligature"],
        "link": "https://en.wikipedia.org/wiki/Ligature_(writing)#Ligatures_in_Unicode_(Latin_alphabets)",
    },
    {
        "name": "AE ligature",
        "majuscule": ("AE", "Æ"),
        "minuscule": ("ae", "æ"),
        "modifiers": ["ligature"],
        "link": "https://en.wikipedia.org/wiki/Ligature_(writing)#Ligatures_in_Unicode_(Latin_alphabets)",
    },
    {
        "name": "AO ligature",
        "majuscule": ("AO", "Ꜵ"),
        "minuscule": ("ao", "ꜵ"),
        "modifiers": ["ligature"],
        "link": "https://en.wikipedia.org/wiki/Ligature_(writing)#Ligatures_in_Unicode_(Latin_alphabets)",
    },
    {
        "name": "AU ligature",
        "majuscule": ("AU", "Ꜷ"),
        "minuscule": ("au", "ꜷ"),
        "modifiers": ["ligature"],
        "link": "https://en.wikipedia.org/wiki/Ligature_(writing)#Ligatures_in_Unicode_(Latin_alphabets)",
    },
    {
        "name": "AV ligature",
        "majuscule": ("AV", "Ꜹ"),
        "minuscule": ("av", "ꜻ"),
        "modifiers": ["ligature"],
        "link": "https://en.wikipedia.org/wiki/Ligature_(writing)#Ligatures_in_Unicode_(Latin_alphabets)",
    },
    {
        "name": "AY ligature",
        "majuscule": ("AY", "Ꜽ"),
        "minuscule": ("ay", "ꜽ"),
        "modifiers": ["ligature"],
        "link": "https://en.wikipedia.org/wiki/Ligature_(writing)#Ligatures_in_Unicode_(Latin_alphabets)",
    },
    {
        "name": "FF ligature",
        "majuscule": None,
        "minuscule": ("ff", "ﬀ"),
        "modifiers": ["ligature"],
        "link": "https://en.wikipedia.org/wiki/Ligature_(writing)#Ligatures_in_Unicode_(Latin_alphabets)",
    },
    {
        "name": "FFI ligature",
        "majuscule": None,
        "minuscule": ("ffi", "ﬃ"),
        "modifiers": ["ligature"],
        "link": "https://en.wikipedia.org/wiki/Ligature_(writing)#Ligatures_in_Unicode_(Latin_alphabets)",
    },
    {
        "name": "FFL ligature",
        "majuscule": None,
        "minuscule": ("ffl", "ﬄ"),
        "modifiers": ["ligature"],
        "link": "https://en.wikipedia.org/wiki/Ligature_(writing)#Ligatures_in_Unicode_(Latin_alphabets)",
    },
    {
        "name": "FI ligature",
        "majuscule": None,
        "minuscule": ("fi", "ﬁ"),
        "modifiers": ["ligature"],
        "link": "https://en.wikipedia.org/wiki/Ligature_(writing)#Ligatures_in_Unicode_(Latin_alphabets)",
    },
    {
        "name": "FL ligature",
        "majuscule": None,
        "minuscule": ("fl", "ﬂ"),
        "modifiers": ["ligature"],
        "link": "https://en.wikipedia.org/wiki/Ligature_(writing)#Ligatures_in_Unicode_(Latin_alphabets)",
    },
    {
        "name": "HV ligature",
        "majuscule": ("Hv", "Ƕ"),
        "minuscule": ("hv", "ƕ"),
        "modifiers": ["ligature"],
        "link": "https://en.wikipedia.org/wiki/Ligature_(writing)#Ligatures_in_Unicode_(Latin_alphabets)",
    },
    {
        "name": "LB ligature",
        "majuscule": None,
        "minuscule": ("lb", "℔"),
        "modifiers": ["ligature"],
        "link": "https://en.wikipedia.org/wiki/Ligature_(writing)#Ligatures_in_Unicode_(Latin_alphabets)",
    },
    {
        "name": "IL ligature",
        "majuscule": ("IL", "Ỻ"),
        "minuscule": ("il", "ỻ"),
        "modifiers": ["ligature"],
        "link": "https://en.wikipedia.org/wiki/Ligature_(writing)#Ligatures_in_Unicode_(Latin_alphabets)",
    },
    {
        "name": "OE ligature",
        "majuscule": ("OE", "Œ"),
        "minuscule": ("oe", "œ"),
        "modifiers": ["ligature"],
        "link": "https://en.wikipedia.org/wiki/Ligature_(writing)#Ligatures_in_Unicode_(Latin_alphabets)",
    },
    {
        "name": "OO ligature",
        "majuscule": ("OO", "Ꝏ"),
        "minuscule": ("oo", "ꝏ"),
        "modifiers": ["ligature"],
        "link": "https://en.wikipedia.org/wiki/Ligature_(writing)#Ligatures_in_Unicode_(Latin_alphabets)",
    },
    {
        "name": "ST ligature",
        "majuscule": None,
        "minuscule": ("st", "ﬆ"),
        "modifiers": ["ligature"],
        "link": "https://en.wikipedia.org/wiki/Ligature_(writing)#Ligatures_in_Unicode_(Latin_alphabets)",
    },
    {
        "name": "TZ ligature",
        "majuscule": ("TZ", "Ꜩ"),
        "minuscule": ("tz", "ꜩ"),
        "modifiers": ["ligature"],
        "link": "https://en.wikipedia.org/wiki/Ligature_(writing)#Ligatures_in_Unicode_(Latin_alphabets)",
    },
    {
        "name": "UE ligature",
        "majuscule": None,
        "minuscule": ("ue", "ᵫ"),
        "modifiers": ["ligature"],
        "link": "https://en.wikipedia.org/wiki/Ligature_(writing)#Ligatures_in_Unicode_(Latin_alphabets)",
    },
    {
        "name": "UO ligature",
        "majuscule": None,
        "minuscule": ("uo", "ꭣ"),
        "modifiers": ["ligature"],
        "link": "https://en.wikipedia.org/wiki/Ligature_(writing)#Ligatures_in_Unicode_(Latin_alphabets)",
    },
    {
        "name": "VV ligature",
        "majuscule": ("VV", "W"), # literally just capital W (U+OO57)
        "minuscule": ("vv", "w"), # literally just lowercase W (U+OO77)
        "modifiers": ["ligature"],
        "link": "https://en.wikipedia.org/wiki/Ligature_(writing)#Ligatures_in_Unicode_(Latin_alphabets)",
    },
    {
        "name": "VY ligature",
        "majuscule": ("VY", "Ꝡ"),
        "minuscule": ("vy", "ꝡ"),
        "modifiers": ["ligature"],
        "link": "https://en.wikipedia.org/wiki/Ligature_(writing)#Ligatures_in_Unicode_(Latin_alphabets)",
    },
    {
        "name": "Eszett (SZ ligature)",
        "majuscule": ("SZ", "ẞ"),
        "minuscule": ("sz", "ß"),
        "modifiers": ["ligature"],
        "link": "https://en.wikipedia.org/wiki/%C3%9F",
    },
    #  _                        __
    # | |_ _ __ __ _ _ __  ___ / _| ___  _ __ _ __ ___  ___
    # | __| '__/ _` | '_ \/ __| |_ / _ \| '__| '_ ` _ \/ __|
    # | |_| | | (_| | | | \__ \  _| (_) | |  | | | | | \__ \
    #  \__|_|  \__,_|_| |_|___/_|  \___/|_|  |_| |_| |_|___/
    #
    {
        "name": "Schwa",
        "majuscule": ("E", "Ə"),
        "minuscule": ("e", "ə"),
        "modifiers": ["turned"],
        "link": "https://en.wikipedia.org/wiki/Mid_central_vowel",
    },
    {
        "name": "Reversed C",
        "majuscule": ("C", "Ↄ"),
        "minuscule": ("c", "ↄ"),
        "modifiers": ["reversed"],
        "link": "https://en.wikipedia.org/wiki/Claudian_letters", # TODO research these
    },
    {
        "name": "Turned F",
        "majuscule": ("F", "Ⅎ"),
        "minuscule": ("f", "ⅎ"),
        "modifiers": ["turned"],
        "link": "https://en.wikipedia.org/wiki/Claudian_letters", # TODO research these
    },
    #  _ _             _                        _ _                 _ _   _
    # | (_) __ _  __ _| |_ _   _ _ __ ___    __| (_) __ _  ___ _ __(_) |_(_) ___ ___
    # | | |/ _` |/ _` | __| | | | '__/ _ \  / _` | |/ _` |/ __| '__| | __| |/ __/ __|
    # | | | (_| | (_| | |_| |_| | | |  __/ | (_| | | (_| | (__| |  | | |_| | (__\__ \
    # |_|_|\__, |\__,_|\__|\__,_|_|  \___|  \__,_|_|\__,_|\___|_|  |_|\__|_|\___|___/
    #      |___/
    {
        "name": "AE ligature with acute",
        "majuscule": ("AE", "Ǽ"),
        "minuscule": ("ae", "ǽ"),
        "modifiers": ["ligature", "acute"],
        "link": "https://en.wikipedia.org/wiki/%C3%86",
    },
    {
        "name": "AE ligature with macron",
        "majuscule": ("AE", "Ǣ"),
        "minuscule": ("ae", "ǣ"),
        "modifiers": ["ligature", "macron"],
        "link": "https://en.wikipedia.org/wiki/%C3%86",
    },
    #  _                             _   _ _             _
    # | |_ _   _ _ __ _ __   ___  __| | | (_) __ _  __ _| |_ _   _ _ __ ___  ___
    # | __| | | | '__| '_ \ / _ \/ _` | | | |/ _` |/ _` | __| | | | '__/ _ \/ __|
    # | |_| |_| | |  | | | |  __/ (_| | | | | (_| | (_| | |_| |_| | | |  __/\__ \
    #  \__|\__,_|_|  |_| |_|\___|\__,_| |_|_|\__, |\__,_|\__|\__,_|_|  \___||___/
    #                                        |___/
    {
        "name": "AE ligature turned",
        "majuscule": None,
        "minuscule": ("ae", "ᴂ"),
        "modifiers": ["ligature", "turned"],
        "link": "https://en.wiktionary.org/wiki/%E1%B4%82#Translingual",
    },
    #      _ _                 _ _   _
    #   __| (_) __ _  ___ _ __(_) |_(_) ___ ___
    #  / _` | |/ _` |/ __| '__| | __| |/ __/ __|
    # | (_| | | (_| | (__| |  | | |_| | (__\__ \
    #  \__,_|_|\__,_|\___|_|  |_|\__|_|\___|___/
    #
    {
        "name": "A with ogonek",
        "majuscule": ("A", "Ą"),
        "minuscule": ("a", "ą"),
        "modifiers": ["ogonek"], #TODO look more into ogonek
        "link": "https://en.wikipedia.org/wiki/%C4%84",
    },
    {
        "name": "B with hook",
        "majuscule": ("B", "Ɓ"),
        "minuscule": ("b", "ɓ"),
        "modifiers": ["hook"],
        "link": "https://en.wikipedia.org/wiki/%C6%81",
    },
    {
        "name": "C with hook",
        "majuscule": ("C", "Ƈ"),
        "minuscule": ("c", "ƈ"),
        "modifiers": ["hook"],
        "link": "https://en.wikipedia.org/wiki/%C6%87",
    },
    {
        "name": "C with cedilla",
        "majuscule": ("C", "Ç"),
        "minuscule": ("c", "ç"),
        "modifiers": ["cedilla"],
        "link": "https://en.wikipedia.org/wiki/%C3%87",
    },
    {
        "name": "D with stroke",
        "majuscule": ("D", "Đ"),
        "minuscule": ("d", "đ"),
        "modifiers": ["stroke"],
        "link": "https://en.wikipedia.org/wiki/D_with_stroke",
    },
    {
        "name": "D with hook",
        "majuscule": ("D", "Ɗ"),
        "minuscule": ("d", "ɗ"),
        "modifiers": ["hook"],
        "link": "https://en.wikipedia.org/wiki/%C6%8A",
    },
    {
        "name": "E with ogonek",
        "majuscule": ("E", "Ę"),
        "minuscule": ("e", "ę"),
        "modifiers": ["ogonek"],
        "link": "https://en.wikipedia.org/wiki/%C4%98",
    },
    {
        "name": "E with cedilla",
        "majuscule": ("E", "Ȩ"),
        "minuscule": ("e", "ȩ"),
        "modifiers": ["cedilla"],
        "link": "https://en.wikipedia.org/wiki/Cedilla",
    },
    {
        "name": "F with hook",
        "majuscule": ("F", "Ƒ"),
        "minuscule": ("f", "ƒ"),
        "modifiers": ["hook"],
        "link": "https://en.wikipedia.org/wiki/%C6%91",
    },
    {
        "name": "G with stroke",
        "majuscule": ("G", "Ǥ"),
        "minuscule": ("g", "ǥ"),
        "modifiers": ["stroke"],
        "link": "https://en.wikipedia.org/wiki/G_with_stroke",
    },
    {
        "name": "G with hook",
        "majuscule": ("G", "Ɠ"),
        "minuscule": ("g", "ɠ"),
        "modifiers": ["hook"],
        "link": "https://en.wikipedia.org/wiki/G_with_hook",
    },
    {
        "name": "H with stroke",
        "majuscule": ("H", "Ħ"),
        "minuscule": ("h", "ħ"),
        "modifiers": ["stroke"],
        "link": "https://en.wikipedia.org/wiki/H_with_stroke",
    },
    {
        "name": "I with ogonek",
        "majuscule": ("I", "Į"),
        "minuscule": ("i", "į"),
        "modifiers": ["ogonek"],
        "link": "https://en.wikipedia.org/wiki/%C4%AE",
    },
    {
        "name": "I with bar",
        "majuscule": ("I", "Ɨ"),
        "minuscule": ("i", "ɨ"),
        "modifiers": ["stroke"],
        "link": "https://en.wikipedia.org/wiki/I_with_bar", # TODO look more into bar
    },
    {
        "name": "K with hook",
        "majuscule": ("K", "Ƙ"),
        "minuscule": ("k", "ƙ"),
        "modifiers": ["hook"],
        "link": "https://en.wikipedia.org/wiki/%C6%98",
    },
    {
        "name": "L with stroke",
        "majuscule": ("L", "Ł"),
        "minuscule": ("l", "ł"),
        "modifiers": ["slash"], # TODO look more into stroke
        "link": "https://en.wikipedia.org/wiki/%C5%81",
    },
    {
        "name": "L with bar",
        "majuscule": ("L", "Ƚ"),
        "minuscule": ("l", "ƚ"),
        "modifiers": ["stroke"],
        "link": "https://en.wikipedia.org/wiki/L_with_bar",
    },
    {
        "name": "O with ogonek",
        "majuscule": ("Q", "Ǫ"),
        "minuscule": ("q", "ǫ"),
        "modifiers": ["ogonek"],
        "link": "https://en.wikipedia.org/wiki/%C7%AA",
    },
    {
        "name": "O with stroke",
        "majuscule": ("O", "Ø"),
        "minuscule": ("o", "ø"),
        "modifiers": ["slash"],
        "link": "https://en.wikipedia.org/wiki/%C3%98",
    },
    {
        "name": "O with horn",
        "majuscule": ("O", "Ơ"),
        "minuscule": ("o", "ơ"),
        "modifiers": ["horn"],
        "link": "https://en.wikipedia.org/wiki/%C6%A0",
    },
    {
        "name": "P with hook",
        "majuscule": ("P", "Ƥ"),
        "minuscule": ("p", "ƥ"),
        "modifiers": ["hook"],
        "link": "https://en.wikipedia.org/wiki/%C6%A4",
    },
    {
        "name": "R with stroke",
        "majuscule": ("R", "Ɍ"),
        "minuscule": ("r", "ɍ"),
        "modifiers": ["stroke"],
        "link": "https://en.wikipedia.org/wiki/R_with_stroke",
    },
    {
        "name": "S with cedilla",
        "majuscule": ("S", "Ş"),
        "minuscule": ("s", "ş"),
        "modifiers": ["cedilla"],
        "link": "https://en.wikipedia.org/wiki/%C5%9E",
    },
    {
        "name": "T with hook",
        "majuscule": ("T", "Ƭ"),
        "minuscule": ("t", "ƭ"),
        "modifiers": ["hook"],
        "link": "https://en.wikipedia.org/wiki/%C6%AC",
    },
    {
        "name": "T with cedilla",
        "majuscule": ("T", "Ţ"),
        "minuscule": ("t", "ţ"),
        "modifiers": ["cedilla"],
        "link": "https://en.wikipedia.org/wiki/%C5%A2",
    },
    {
        "name": "T with stroke",
        "majuscule": ("T", "Ŧ"),
        "minuscule": ("t", "ŧ"),
        "modifiers": ["stroke"],
        "link": "https://en.wikipedia.org/wiki/T_with_stroke",
    },
    {
        "name": "U with ogonek",
        "majuscule": ("U", "Ų"),
        "minuscule": ("u", "ų"),
        "modifiers": ["ogonek"],
        "link": "https://en.wikipedia.org/wiki/%C5%B2",
    },
    {
        "name": "U with horn",
        "majuscule": ("U", "Ư"),
        "minuscule": ("u", "ư"),
        "modifiers": ["horn"],
        "link": "https://en.wikipedia.org/wiki/%C6%AF",
    },
    {
        "name": "U with bar",
        "majuscule": ("U", "Ʉ"),
        "minuscule": ("u", "ʉ"),
        "modifiers": ["stroke"],
        "link": "https://en.wikipedia.org/wiki/U_with_bar",
    },
    {
        "name": "Y with hook",
        "majuscule": ("Y", "Ƴ"),
        "minuscule": ("y", "ƴ"),
        "modifiers": ["hook"],
        "link": "https://en.wikipedia.org/wiki/%C6%B3",
    },
    {
        "name": "A with acute",
        "majuscule": ("A", "Á"),
        "minuscule": ("a", "á"),
        "modifiers": ["acute"],
        "link": "https://en.wikipedia.org/wiki/%C3%81",
    },
    {
        "name": "A with grave",
        "majuscule": ("A", "À"),
        "minuscule": ("a", "à"),
        "modifiers": ["grave"],
        "link": "https://en.wikipedia.org/wiki/%C3%80",
    },
    {
        "name": "A with dot above",
        "majuscule": ("A", "Ȧ"),
        "minuscule": ("a", "ȧ"),
        "modifiers": ["dotAbove"],
        "link": "https://en.wikipedia.org/wiki/%C8%A6",
    },
    {
        "name": "A with circumflex",
        "majuscule": ("A", "Â"),
        "minuscule": ("a", "â"),
        "modifiers": ["circumflex"],
        "link": "https://en.wikipedia.org/wiki/%C3%82",
    },
    {
        "name": "A with diaeresis",
        "majuscule": ("A", "Ä"),
        "minuscule": ("a", "ä"),
        "modifiers": ["diaeresis"],
        "link": "https://en.wikipedia.org/wiki/%C3%84",
    },
    {
        "name": "A with diaeresis and macron",
        "majuscule": ("A", "Ǟ"),
        "minuscule": ("a", "ǟ"),
        "modifiers": ["diaeresis", "macron"],
        "link": "https://en.wikipedia.org/wiki/Livonian_language#Alphabet",
    },
    {
        "name": "A with caron",
        "majuscule": ("A", "Ǎ"),
        "minuscule": ("a", "ǎ"),
        "modifiers": ["caron"],
        "link": "https://en.wikipedia.org/wiki/Caron",
    },
    {
        "name": "A with breve",
        "majuscule": ("A", "Ă"),
        "minuscule": ("a", "ă"),
        "modifiers": ["breve"],
        "link": "https://en.wikipedia.org/wiki/%C4%82",
    },
    {
        "name": "A with macron",
        "majuscule": ("A", "Ā"),
        "minuscule": ("a", "ā"),
        "modifiers": ["macron"],
        "link": "https://en.wikipedia.org/wiki/%C4%80",
    },
    {
        "name": "A with tilde",
        "majuscule": ("A", "Ã"),
        "minuscule": ("a", "ã"),
        "modifiers": ["tilde"],
        "link": "https://en.wikipedia.org/wiki/%C3%83",
    },
    {
        "name": "A with ring above",
        "majuscule": ("A", "Å"),
        "minuscule": ("a", "å"),
        "modifiers": ["ringAbove"],
        "link": "https://en.wikipedia.org/wiki/%C3%85",
    },
    {
        "name": "B with dot below",
        "majuscule": ("B", "Ḅ"),
        "minuscule": ("b", "ḅ"),
        "modifiers": ["dotBelow"],
        "link": "https://en.wikipedia.org/wiki/Dot_(diacritic)",
    },
    {
        "name": "C with acute",
        "majuscule": ("C", "Ć"),
        "minuscule": ("c", "ć"),
        "modifiers": ["acute"],
        "link": "https://en.wikipedia.org/wiki/%C4%86",
    },
    {
        "name": "C with dot above",
        "majuscule": ("C", "Ċ"),
        "minuscule": ("c", "ċ"),
        "modifiers": ["dotAbove"],
        "link": "https://en.wikipedia.org/wiki/%C4%8A",
    },
    {
        "name": "C with circumflex",
        "majuscule": ("C", "Ĉ"),
        "minuscule": ("c", "ĉ"),
        "modifiers": ["circumflex"],
        "link": "https://en.wikipedia.org/wiki/%C4%88",
    },
    {
        "name": "C with caron",
        "majuscule": ("C", "Č"),
        "minuscule": ("c", "č"),
        "modifiers": ["caron"],
        "link": "https://en.wikipedia.org/wiki/%C4%8C",
    },
    {
        "name": "D with dot below",
        "majuscule": ("D", "Ḍ"),
        "minuscule": ("d", "ḍ"),
        "modifiers": ["dotBelow"],
        "link": "https://en.wikipedia.org/wiki/%E1%B8%8C",
    },
    {
        "name": "D with cedilla",
        "majuscule": ("D", "Ḑ"),
        "minuscule": ("d", "ḑ"),
        "modifiers": ["cedilla"],
        "link": "https://en.wikipedia.org/wiki/%E1%B8%90",
    },
    {
        "name": "D with circumflex",
        "majuscule": ("D", "Ḓ"),
        "minuscule": ("d", "ḓ"),
        "modifiers": ["circumflex"],
        "link": "https://en.wikipedia.org/wiki/Circumflex",
    },
    {
        "name": "E with acute",
        "majuscule": ("E", "É"),
        "minuscule": ("e", "é"),
        "modifiers": ["acute"],
        "link": "https://en.wikipedia.org/wiki/%C3%89",
    },
    {
        "name": "E with grave",
        "majuscule": ("E", "È"),
        "minuscule": ("e", "è"),
        "modifiers": ["grave"],
        "link": "https://en.wikipedia.org/wiki/%C3%88",
    },
    {
        "name": "E with dot above",
        "majuscule": ("E", "Ė"),
        "minuscule": ("e", "ė"),
        "modifiers": ["dotAbove"],
        "link": "https://en.wikipedia.org/wiki/%C4%96",
    },
    {
        "name": "E with circumflex",
        "majuscule": ("E", "Ê"),
        "minuscule": ("e", "ê"),
        "modifiers": ["circumflex"],
        "link": "https://en.wikipedia.org/wiki/%C3%8A",
    },
    {
        "name": "E with diaeresis",
        "majuscule": ("E", "Ë"),
        "minuscule": ("e", "ë"),
        "modifiers": ["diaeresis"],
        "link": "https://en.wikipedia.org/wiki/%C3%8B",
    },
    {
        "name": "E with caron",
        "majuscule": ("E", "Ě"),
        "minuscule": ("e", "ě"),
        "modifiers": ["caron"],
        "link": "https://en.wikipedia.org/wiki/%C4%9A",
    },
    {
        "name": "E with breve",
        "majuscule": ("E", "Ĕ"),
        "minuscule": ("e", "ĕ"),
        "modifiers": ["breve"],
        "link": "https://en.wikipedia.org/wiki/Breve#Letters_with_breve",
    },
    {
        "name": "E with macron",
        "majuscule": ("E", "Ē"),
        "minuscule": ("e", "ē"),
        "modifiers": ["macron"],
        "link": "https://en.wikipedia.org/wiki/Macron_(diacritic)",
    },
    {
        "name": "E with tilde",
        "majuscule": ("E", "Ẽ"),
        "minuscule": ("e", "ẽ"),
        "modifiers": ["tilde"],
        "link": "https://en.wikipedia.org/wiki/%E1%BA%BC",
    },
    {
        "name": "E with dot below",
        "majuscule": ("E", "Ẹ"),
        "minuscule": ("e", "ẹ"),
        "modifiers": ["dotBelow"],
        "link": "https://en.wikipedia.org/wiki/Dot_(diacritic)",
    },
    {
        "name": "G with acute",
        "majuscule": ("G", "Ǵ"),
        "minuscule": ("g", "ǵ"),
        "modifiers": ["acute"],
        "link": "https://en.wikipedia.org/wiki/%C7%B4",
    },
    {
        "name": "G with dot above",
        "majuscule": ("G", "Ġ"),
        "minuscule": ("g", "ġ"),
        "modifiers": ["dotAbove"],
        "link": "https://en.wikipedia.org/wiki/%C4%A0",
    },
    {
        "name": "G with circumflex",
        "majuscule": ("G", "Ĝ"),
        "minuscule": ("g", "ĝ"),
        "modifiers": ["circumflex"],
        "link": "https://en.wikipedia.org/wiki/%C4%9C",
    },
    {
        "name": "G with caron",
        "majuscule": ("G", "Ǧ"),
        "minuscule": ("g", "ǧ"),
        "modifiers": ["caron"],
        "link": "https://en.wikipedia.org/wiki/%C7%A6",
    },
    {
        "name": "G with breve",
        "majuscule": ("G", "Ğ"),
        "minuscule": ("g", "ğ"),
        "modifiers": ["breve"],
        "link": "https://en.wikipedia.org/wiki/%C4%9E",
    },
    {
        "name": "G with cedilla",
        "majuscule": ("G", "Ģ"),
        "minuscule": ("g", "ģ"),
        "modifiers": ["cedilla"],
        "link": "https://en.wikipedia.org/wiki/%C4%A2",
    },
    {
        "name": "H with circumflex",
        "majuscule": ("H", "Ĥ"),
        "minuscule": ("h", "ĥ"),
        "modifiers": ["circumflex"],
        "link": "https://en.wikipedia.org/wiki/%C4%A4",
    },
    {
        "name": "H with dot below",
        "majuscule": ("H", "Ḥ"),
        "minuscule": ("h", "ḥ"),
        "modifiers": ["dotBelow"],
        "link": "https://en.wikipedia.org/wiki/Dot_(diacritic)",
    },
    {
        "name": "I with acute",
        "majuscule": ("I", "Í"),
        "minuscule": ("i", "í"),
        "modifiers": ["acute"],
        "link": "https://en.wikipedia.org/wiki/%C3%8D",
    },
    {
        "name": "I with grave",
        "majuscule": ("I", "Ì"),
        "minuscule": ("i", "ì"),
        "modifiers": ["grave"],
        "link": "https://en.wikipedia.org/wiki/%C3%8C",
    },
    {
        "name": "I with dot above",
        "majuscule": ("I", "İ"),
        "minuscule": ("i", "i"), # literally just lowercase i, U+0069
        "modifiers": ["dotAbove"],
        "link": "https://en.wikipedia.org/wiki/%C4%B0",
    },
    {
        "name": "I with circumflex",
        "majuscule": ("I", "Î"),
        "minuscule": ("i", "î"),
        "modifiers": ["circumflex"],
        "link": "https://en.wikipedia.org/wiki/%C3%8E",
    },
    {
        "name": "I with diaeresis",
        "majuscule": ("I", "Ï"),
        "minuscule": ("i", "ï"),
        "modifiers": ["diaeresis"],
        "link": "https://en.wikipedia.org/wiki/%C3%8F",
    },
    {
        "name": "I with caron",
        "majuscule": ("I", "Ǐ"),
        "minuscule": ("i", "ǐ"),
        "modifiers": ["caron"],
        "link": "https://en.wikipedia.org/wiki/Caron",
    },
    {
        "name": "I with breve",
        "majuscule": ("I", "Ĭ"),
        "minuscule": ("i", "ĭ"),
        "modifiers": ["breve"],
        "link": "https://en.wikipedia.org/wiki/Breve",
    },
    {
        "name": "I with macron",
        "majuscule": ("I", "Ī"),
        "minuscule": ("i", "ī"),
        "modifiers": ["macron"],
        "link": "https://en.wikipedia.org/wiki/Macron_(diacritic)",
    },
    {
        "name": "I with tilde",
        "majuscule": ("I", "Ĩ"),
        "minuscule": ("i", "ĩ"),
        "modifiers": ["tilde"],
        "link": "https://en.wikipedia.org/wiki/Tilde",
    },
    {
        "name": "I with dot below",
        "majuscule": ("I", "Ị"),
        "minuscule": ("i", "ị"),
        "modifiers": ["dotBelow"],
        "link": "https://en.wikipedia.org/wiki/Dot_(diacritic)",
    },
    {
        "name": "J with circumflex",
        "majuscule": ("J", "Ĵ"),
        "minuscule": ("j", "ĵ"),
        "modifiers": ["circumflex"],
        "link": "https://en.wikipedia.org/wiki/%C4%B4",
    },
    {
        "name": "K with cedilla",
        "majuscule": ("K", "Ķ"),
        "minuscule": ("k", "ķ"),
        "modifiers": ["cedilla"],
        "link": "https://en.wikipedia.org/wiki/%C4%B6",
    },
    {
        "name": "K with caron",
        "majuscule": ("K", "Ǩ"),
        "minuscule": ("k", "ǩ"),
        "modifiers": ["caron"],
        "link": "https://en.wikipedia.org/wiki/%C7%A8",
    },
    {
        "name": "L with acute",
        "majuscule": ("L", "Ĺ"),
        "minuscule": ("l", "ĺ"),
        "modifiers": ["acute"],
        "link": "https://en.wikipedia.org/wiki/Acute_accent",
    },
    {
        "name": "L with cedilla",
        "majuscule": ("L", "Ļ"),
        "minuscule": ("l", "ļ"),
        "modifiers": ["cedilla"],
        "link": "https://en.wikipedia.org/wiki/Cedilla",
    },
    {
        "name": "L with caron",
        "majuscule": ("L", "Ľ"),
        "minuscule": ("l", "ľ"),
        "modifiers": ["caron"],
        "link": "https://en.wikipedia.org/wiki/%C4%BD",
    },
    {
        "name": "L with interpunct",
        "majuscule": ("L", "Ŀ"),
        "minuscule": ("l", "ŀ"),
        "modifiers": ["interpunct"],
        "link": "https://en.wikipedia.org/wiki/Interpunct#Catalan",
    },
    {
        "name": "L with dot below",
        "majuscule": ("L", "Ḷ"),
        "minuscule": ("l", "ḷ"),
        "modifiers": ["dotBelow"],
        "link": "https://en.wikipedia.org/wiki/%E1%B8%B6",
    },
    {
        "name": "L with circumflex",
        "majuscule": ("L", "Ḽ"),
        "minuscule": ("l", "ḽ"),
        "modifiers": ["circumflex"],
        "link": "https://en.wikipedia.org/wiki/Circumflex",
    },
    {
        "name": "N with acute",
        "majuscule": ("N", "Ń"),
        "minuscule": ("n", "ń"),
        "modifiers": ["acute"],
        "link": "https://en.wikipedia.org/wiki/%C5%83",
    },
    {
        "name": "N with dot above",
        "majuscule": ("N", "Ṅ"),
        "minuscule": ("n", "ṅ"),
        "modifiers": ["dotAbove"],
        "link": "https://en.wikipedia.org/wiki/%E1%B9%84",
    },
    {
        "name": "N with caron",
        "majuscule": ("N", "Ň"),
        "minuscule": ("n", "ň"),
        "modifiers": ["caron"],
        "link": "https://en.wikipedia.org/wiki/%C5%87",
    },
    {
        "name": "N with tilde",
        "majuscule": ("N", "Ñ"),
        "minuscule": ("n", "ñ"),
        "modifiers": ["tilde"],
        "link": "https://en.wikipedia.org/wiki/%C3%91",
    },
    {
        "name": "N with cedilla",
        "majuscule": ("N", "Ņ"),
        "minuscule": ("n", "ņ"),
        "modifiers": ["cedilla"],
        "link": "https://en.wikipedia.org/wiki/Cedilla",
    },
    {
        "name": "N with circumflex",
        "majuscule": ("N", "Ṋ"),
        "minuscule": ("n", "ṋ"),
        "modifiers": ["circumflex"],
        "link": "https://en.wikipedia.org/wiki/Circumflex",
    },
    {
        "name": "O with acute",
        "majuscule": ("O", "Ó"),
        "minuscule": ("o", "ó"),
        "modifiers": ["acute"],
        "link": "https://en.wikipedia.org/wiki/%C3%93",
    },
    {
        "name": "O with grave",
        "majuscule": ("O", "Ò"),
        "minuscule": ("o", "ò"),
        "modifiers": ["grave"],
        "link": "https://en.wikipedia.org/wiki/%C3%92",
    },
    {
        "name": "O with dot above",
        "majuscule": ("O", "Ȯ"),
        "minuscule": ("o", "ȯ"),
        "modifiers": ["dotAbove"],
        "link": "https://en.wikipedia.org/wiki/Dot_(diacritic)",
    },
    {
        "name": "O with dot above and macron",
        "majuscule": ("O", "Ȱ"),
        "minuscule": ("o", "ȱ"),
        "modifiers": ["dotAbove", "macron"],
        "link": "https://en.wikipedia.org/wiki/Dot_(diacritic)",
    },
    {
        "name": "O with circumflex",
        "majuscule": ("O", "Ô"),
        "minuscule": ("o", "ô"),
        "modifiers": ["circumflex"],
        "link": "https://en.wikipedia.org/wiki/Circumflex",
    },
    {
        "name": "O with diaeresis",
        "majuscule": ("O", "Ö"),
        "minuscule": ("o", "ö"),
        "modifiers": ["diaeresis"],
        "link": "https://en.wikipedia.org/wiki/%C3%96",
    },
    {
        "name": "O with diaeresis and macron",
        "majuscule": ("O", "Ȫ"),
        "minuscule": ("o", "ȫ"),
        "modifiers": ["diaeresis", "macron"],
        "link": "https://en.wikipedia.org/wiki/%C3%96",
    },
    {
        "name": "O with caron",
        "majuscule": ("O", "Ǒ"),
        "minuscule": ("o", "ǒ"),
        "modifiers": ["caron"],
        "link": "https://en.wikipedia.org/wiki/Caron",
    },
    {
        "name": "O with breve",
        "majuscule": ("O", "Ŏ"),
        "minuscule": ("o", "ŏ"),
        "modifiers": ["breve"],
        "link": "https://en.wikipedia.org/wiki/Breve",
    },
    {
        "name": "O with macron",
        "majuscule": ("O", "Ō"),
        "minuscule": ("o", "ō"),
        "modifiers": ["macron"],
        "link": "https://en.wikipedia.org/wiki/Macron_(diacritic)",
    },
    {
        "name": "O with tilde",
        "majuscule": ("O", "Õ"),
        "minuscule": ("o", "õ"),
        "modifiers": ["tilde"],
        "link": "https://en.wikipedia.org/wiki/%C3%95"
    },
    {
        "name": "O with tilde and macron",
        "majuscule": ("O", "Ȭ"),
        "minuscule": ("o", "ȭ"),
        "modifiers": ["tilde", "macron"],
        "link": "https://en.wikipedia.org/wiki/Livonian_language#Alphabet",
    },
    {
        "name": "O with double acute",
        "majuscule": ("O", "Ő"),
        "minuscule": ("o", "ő"),
        "modifiers": ["acuteDoubled"],
        "link": "https://en.wikipedia.org/wiki/%C5%90",
    },
    {
        "name": "O with dot below",
        "majuscule": ("O", "Ọ"),
        "minuscule": ("o", "ọ"),
        "modifiers": ["dotBelow"],
        "link": "https://en.wikipedia.org/wiki/Dot_(diacritic)",
    },
    {
        "name": "O with slash and acute",
        "majuscule": ("O", "Ǿ"),
        "minuscule": ("o", "ǿ"),
        "modifiers": ["slash", "acute"],
        "link": "https://en.wikipedia.org/wiki/%C3%98#%C7%BE",
    },
    {
        "name": "O with horn",
        "majuscule": ("O", "Ơ"),
        "minuscule": ("o", "ơ"),
        "modifiers": ["horn"],
        "link": "https://en.wikipedia.org/wiki/%C6%A0",
    },
    {
        "name": "R with acute",
        "majuscule": ("R", "Ŕ"),
        "minuscule": ("r", "ŕ"),
        "modifiers": ["acute"],
        "link": "https://en.wikipedia.org/wiki/%C5%94",
    },
    {
        "name": "R with caron",
        "majuscule": ("R", "Ř"),
        "minuscule": ("r", "ř"),
        "modifiers": ["caron"],
        "link": "https://en.wikipedia.org/wiki/%C5%98",
    },
    {
        "name": "R with cedilla",
        "majuscule": ("R", "Ŗ"),
        "minuscule": ("r", "ŗ"),
        "modifiers": ["cedilla"],
        "link": "https://en.wikipedia.org/wiki/Cedilla",
    },
    {
        "name": "R with dot below",
        "majuscule": ("R", "Ṛ"),
        "minuscule": ("r", "ṛ"),
        "modifiers": ["dotBelow"],
        "link": "https://en.wikipedia.org/wiki/%E1%B9%9A",
    },
    {
        "name": "S with acute",
        "majuscule": ("S", "Ś"),
        "minuscule": ("s", "ś"),
        "modifiers": ["acute"],
        "link": "https://en.wikipedia.org/wiki/%C5%9A",
    },
    {
        "name": "S with caron",
        "majuscule": ("S", "Ŝ"),
        "minuscule": ("s", "ŝ"),
        "modifiers": ["caron"],
        "link": "https://en.wikipedia.org/wiki/%C5%9C",
    },
    {
        "name": "S with dot above",
        "majuscule": ("S", "Ṡ"),
        "minuscule": ("s", "ṡ"), # TODO add "ẛ"
        "modifiers": ["dotAbove"],
        "link": "https://en.wikipedia.org/wiki/%E1%B9%A0",
    },
    {
        "name": "S with caron",
        "majuscule": ("S", "Š"),
        "minuscule": ("s", "š"),
        "modifiers": ["caron"],
        "link": "https://en.wikipedia.org/wiki/%C5%A0",
    },
    {
        "name": "S with comma below",
        "majuscule": ("S", "Ș"),
        "minuscule": ("s", "ș"),
        "modifiers": ["commaBelow"],
        "link": "https://en.wikipedia.org/wiki/%C8%98",
    },
    {
        "name": "S with dot below",
        "majuscule": ("S", "Ș"),
        "minuscule": ("s", "ș"),
        "modifiers": ["dotBelow"],
        "link": "https://en.wikipedia.org/wiki/%E1%B9%A2",
    },
    {
        "name": "T with caron",
        "majuscule": ("T", "Ť"),
        "minuscule": ("t", "ť"),
        "modifiers": ["caron"],
        "link": "https://en.wikipedia.org/wiki/%C5%A4",
    },
    {
        "name": "T with comma",
        "majuscule": ("T", "Ț"),
        "minuscule": ("t", "ț"),
        "modifiers": ["commaBelow"],
        "link": "https://en.wikipedia.org/wiki/%C8%9A",
    },
    {
        "name": "T with dot below",
        "majuscule": ("T", "Ṭ"),
        "minuscule": ("t", "ṭ"),
        "modifiers": ["dotBelow"],
        "link": "https://en.wikipedia.org/wiki/%E1%B9%AC",
    },
    {
        "name": "T with circumflex",
        "majuscule": ("T", "Ṱ"),
        "minuscule": ("t", "ṱ"),
        "modifiers": ["circumflex"],
        "link": "https://en.wikipedia.org/wiki/Circumflex",
    },
    {
        "name": "U with acute",
        "majuscule": ("U", "Ú"),
        "minuscule": ("u", "ú"),
        "modifiers": ["acute"],
        "link": "https://en.wikipedia.org/wiki/%C3%9A",
    },
    {
        "name": "U with grave",
        "majuscule": ("U", "Ù"),
        "minuscule": ("u", "ù"),
        "modifiers": ["grave"],
        "link": "https://en.wikipedia.org/wiki/Grave_accent",
    },
    {
        "name": "U with circumflex",
        "majuscule": ("U", "Û"),
        "minuscule": ("u", "û"),
        "modifiers": ["circumflex"],
        "link": "https://en.wikipedia.org/wiki/%C3%9B",
    },
    {
        "name": "U with diaeresis",
        "majuscule": ("U", "Ü"),
        "minuscule": ("u", "ü"),
        "modifiers": ["diaeresis"],
        "link": "https://en.wikipedia.org/wiki/%C3%9C",
    },
    {
        "name": "U with caron",
        "majuscule": ("U", "Ǔ"),
        "minuscule": ("u", "ǔ"),
        "modifiers": ["caron"],
        "link": "https://en.wikipedia.org/wiki/Caron",
    },
    {
        "name": "U with breve",
        "majuscule": ("U", "Ŭ"),
        "minuscule": ("u", "ŭ"),
        "modifiers": ["breve"],
        "link": "https://en.wikipedia.org/wiki/%C5%AC",
    },
    {
        "name": "U with macron",
        "majuscule": ("U", "Ū"),
        "minuscule": ("u", "ū"),
        "modifiers": ["macron"],
        "link": "https://en.wikipedia.org/wiki/Macron_(diacritic)",
    },
    {
        "name": "U with tilde",
        "majuscule": ("U", "Ũ"),
        "minuscule": ("u", "ũ"),
        "modifiers": ["tilde"],
        "link": "https://en.wikipedia.org/wiki/Tilde",
    },
    {
        "name": "U with double acute",
        "majuscule": ("U", "Ű"),
        "minuscule": ("u", "ű"),
        "modifiers": ["acuteDoubled"],
        "link": "https://en.wikipedia.org/wiki/Double_acute_accent#Letters_with_double_acute",
    },
    {
        "name": "U with ring above",
        "majuscule": ("U", "Ů"),
        "minuscule": ("u", "ů"),
        "modifiers": ["ringAbove"],
        "link": "https://en.wikipedia.org/wiki/Ring_(diacritic)",
    },
    {
        "name": "U with dot below",
        "majuscule": ("U", "Ụ"),
        "minuscule": ("u", "ụ"),
        "modifiers": ["dotBelow"],
        "link": "https://en.wikipedia.org/wiki/Dot_(diacritic)",
    },
    {
        "name": "W with acute",
        "majuscule": ("W", "Ẃ"),
        "minuscule": ("w", "ẃ"),
        "modifiers": ["acute"],
        "link": "https://en.wikipedia.org/wiki/%E1%BA%82",
    },
    {
        "name": "W with grave",
        "majuscule": ("W", "Ẁ"),
        "minuscule": ("w", "ẁ"),
        "modifiers": ["grave"],
        "link": "https://en.wikipedia.org/wiki/Grave_accent",
    },
    {
        "name": "W with circumflex",
        "majuscule": ("W", "Ŵ"),
        "minuscule": ("w", "ŵ"),
        "modifiers": ["circumflex"],
        "link": "https://en.wikipedia.org/wiki/Circumflex",
    },
    {
        "name": "W with diaeresis",
        "majuscule": ("W", "Ẅ"),
        "minuscule": ("w", "ẅ"),
        "modifiers": ["diaeresis"],
        "link": "https://en.wikipedia.org/wiki/Two_dots_(diacritic)",
    },
    {
        "name": "X with dot above",
        "majuscule": ("X", "Ẋ"),
        "minuscule": ("x", "ẋ"),
        "modifiers": ["dotAbove"],
        "link": "https://en.wikipedia.org/wiki/%E1%BA%8A",
    },
    {
        "name": "Y with acute",
        "majuscule": ("Y", "Ý"),
        "minuscule": ("y", "ý"),
        "modifiers": ["acute"],
        "link": "https://en.wikipedia.org/wiki/%C3%9D",
    },
    {
        "name": "Y with grave",
        "majuscule": ("Y", "Ỳ"),
        "minuscule": ("y", "ỳ"),
        "modifiers": ["grave"],
        "link": "https://en.wikipedia.org/wiki/Grave_accent",
    },
    {
        "name": "Y with circumflex",
        "majuscule": ("Y", "Ŷ"),
        "minuscule": ("y", "ŷ"),
        "modifiers": ["circumflex"],
        "link": "https://en.wikipedia.org/wiki/Circumflex",
    },
    {
        "name": "Y with diaeresis",
        "majuscule": ("Y", "Ÿ"),
        "minuscule": ("y", "ÿ"),
        "modifiers": ["diaeresis"],
        "link": "https://en.wikipedia.org/wiki/%C5%B8",
    },
    {
        "name": "Y with macron",
        "majuscule": ("Y", "Ȳ"),
        "minuscule": ("y", "ȳ"),
        "modifiers": ["macron"],
        "link": "https://en.wikipedia.org/wiki/%C8%B2",
    },
    {
        "name": "Y with tilde",
        "majuscule": ("Y", "Ỹ"),
        "minuscule": ("y", "ỹ"),
        "modifiers": ["tilde"],
        "link": "https://en.wikipedia.org/wiki/Tilde",
    },
    {
        "name": "Y with double acute",
        "majuscule": ("Y", "Ӳ"),
        "minuscule": ("y", "ӳ"),
        "modifiers": ["acuteDoubled"],
        "link": "https://en.wikipedia.org/wiki/Double_acute_accent#Letters_with_double_acute",
    },
    {
        "name": "Z with acute",
        "majuscule": ("Z", "Ź"),
        "minuscule": ("z", "ź"),
        "modifiers": ["acute"],
        "link": "https://en.wikipedia.org/wiki/%C5%B9",
    },
    {
        "name": "Z with dot above",
        "majuscule": ("Z", "Ż"),
        "minuscule": ("z", "ż"),
        "modifiers": ["dotAbove"],
        "link": "https://en.wikipedia.org/wiki/%C5%BB",
    },
    {
        "name": "Z with caron",
        "majuscule": ("Z", "Ž"),
        "minuscule": ("z", "ž"),
        "modifiers": ["caron"],
        "link": "https://en.wikipedia.org/wiki/%C5%BD",
    },
    {
        "name": "Z with dot below",
        "majuscule": ("Z", "Ẓ"),
        "minuscule": ("z", "ẓ"),
        "modifiers": ["dotBelow"],
        "link": "https://en.wikipedia.org/wiki/%E1%BA%92",
    },
    {
        "name": "Y with hook above",
        "majuscule": ("Y", "Ỷ"),
        "minuscule": ("y", "ỷ"),
        "modifiers": ["hookAbove"],
        "link": "",
    },
    {
        "name": "Y with dot below",
        "majuscule": ("Y", "Ỵ"),
        "minuscule": ("y", "ỵ"),
        "modifiers": ["dotBelow"],
        "link": "",
    },
    {
        "name": "A with breve and hook above",
        "majuscule": ("A", "Ẳ"),
        "minuscule": ("a", "ẳ"),
        "modifiers": ["breve", "hookAbove"],
        "link": "",
    },
    {
        "name": "A with breve and tilde",
        "majuscule": ("A", "Ẵ"),
        "minuscule": ("a", "ẵ"),
        "modifiers": ["breve", "tilde"],
        "link": "",
    },
    {
        "name": "A with breve and grave",
        "majuscule": ("A", "Ằ"),
        "minuscule": ("a", "ằ"),
        "modifiers": ["breve", "grave"],
        "link": "",
    },
    {
        "name": "A with breve and acute",
        "majuscule": ("A", "Ắ"),
        "minuscule": ("A", "ắ"),
        "modifiers": ["breve", "acute"],
        "link": "",
    },
    {
        "name": "A with hook above",
        "majuscule": ("A", "Ả"),
        "minuscule": ("a", "ả"),
        "modifiers": ["hookAbove"],
        "link": "",
    },
    {
        "name": "A with dot below",
        "majuscule": ("A", "Ạ"),
        "minuscule": ("a", "ạ"),
        "modifiers": ["dotBelow"],
        "link": "",
    },
    {
        "name": "A with breve and dot below",
        "majuscule": ("A", "Ặ"),
        "minuscule": ("a", "ặ"),
        "modifiers": ["breve", "dotBelow"],
        "link": "",
    },
    {
        "name": "A with circumflex and dot below",
        "majuscule": ("A", "Ậ"),
        "minuscule": ("a", "ậ"),
        "modifiers": ["circumflex", "dotBelow"],
        "link": "",
    },
    {
        "name": "A with circumflex and hook above",
        "majuscule": ("A", "Ẩ"),
        "minuscule": ("a", "ẩ"),
        "modifiers": ["circumflex", "hookAbove"],
        "link": "",
    },
    {
        "name": "A with circumflex and tilde",
        "majuscule": ("A", "Ẫ"),
        "minuscule": ("a", "ẫ"),
        "modifiers": ["circumflex", "tilde"],
        "link": "",
    },
    {
        "name": "A with circumflex and grave",
        "majuscule": ("A", "Ầ"),
        "minuscule": ("a", "ầ"),
        "modifiers": ["circumflex", "grave"],
        "link": "",
    },
    {
        "name": "A with circumflex and acute",
        "majuscule": ("A", "Ấ"),
        "minuscule": ("a", "ấ"),
        "modifiers": ["circumflex", "acute"],
        "link": "",
    },
    {
        "name": "O with hook above",
        "majuscule": ("O", "Ỏ"),
        "minuscule": ("o", "ỏ"),
        "modifiers": ["hookAbove"],
        "link": "",
    },
    {
        "name": "O with horn and dot below",
        "majuscule": ("O", "Ợ"),
        "minuscule": ("o", "ợ"),
        "modifiers": ["horn", "dotBelow"],
        "link": "",
    },
    {
        "name": "O with circumflex and dot below",
        "majuscule": ("O", "Ộ"),
        "minuscule": ("o", "ộ"),
        "modifiers": ["circumflex", "dotBelow"],
        "link": "",
    },
    {
        "name": "O with horn and hook above",
        "majuscule": ("O", "Ở"),
        "minuscule": ("o", "ở"),
        "modifiers": ["horn", "hookAbove"],
        "link": "",
    },
    {
        "name": "O with horn and tilde",
        "majuscule": ("O", "Ỡ"),
        "minuscule": ("o", "ỡ"),
        "modifiers": ["horn", "tilde"],
        "link": "",
    },
    {
        "name": "O with horn and grave",
        "majuscule": ("O", "Ờ"),
        "minuscule": ("o", "ờ"),
        "modifiers": ["horn", "grave"],
        "link": "",
    },
    {
        "name": "O with horn and acute",
        "majuscule": ("O", "Ớ"),
        "minuscule": ("o", "ớ"),
        "modifiers": ["horn", "acute"],
        "link": "",
    },
    {
        "name": "O with circumflex and hook above",
        "majuscule": ("O", "Ổ"),
        "minuscule": ("o", "ổ"),
        "modifiers": ["circumflex", "hookAbove"],
        "link": "",
    },
    {
        "name": "O with circumflex and tilde",
        "majuscule": ("O", "Ỗ"),
        "minuscule": ("o", "ỗ"),
        "modifiers": ["circumflex", "tilde"],
        "link": "",
    },
    {
        "name": "O with circumflex and grave",
        "majuscule": ("O", "Ồ"),
        "minuscule": ("o", "ồ"),
        "modifiers": ["circumflex", "grave"],
        "link": "",
    },
    {
        "name": "O with circumflex and acute",
        "majuscule": ("O", "Ố"),
        "minuscule": ("o", "ố"),
        "modifiers": ["circumflex", "acute"],
        "link": "",
    },
    {
        "name": "E with hook above",
        "majuscule": ("E", "Ẻ"),
        "minuscule": ("e", "ẻ"),
        "modifiers": ["hookAbove"],
        "link": "",
    },
    {
        "name": "E with circumflex and dot below",
        "majuscule": ("E", "Ệ"),
        "minuscule": ("e", "ệ"),
        "modifiers": ["circumflex", "dotBelow"],
        "link": "",
    },
    {
        "name": "E with circumflex and hook above",
        "majuscule": ("E", "Ể"),
        "minuscule": ("e", "ể"),
        "modifiers": ["circumflex", "hookAbove"],
        "link": "",
    },
    {
        "name": "E with circumflex and tilde",
        "majuscule": ("E", "Ễ"),
        "minuscule": ("e", "ễ"),
        "modifiers": ["circumflex", "tilde"],
        "link": "",
    },
    {
        "name": "E with circumflex and grave",
        "majuscule": ("E", "Ề"),
        "minuscule": ("e", "ề"),
        "modifiers": ["circumflex", "grave"],
        "link": "",
    },
    {
        "name": "E with circumflex and acute",
        "majuscule": ("E", "Ế"),
        "minuscule": ("e", "ế"),
        "modifiers": ["circumflex", "acute"],
        "link": "",
    },
    {
        "name": "I with hook above",
        "majuscule": ("I", "Ỉ"),
        "minuscule": ("i", "ỉ"),
        "modifiers": ["hookAbove"],
        "link": "",
    },
    {
        "name": "U with hook above",
        "majuscule": ("U", "Ủ"),
        "minuscule": ("u", "ủ"),
        "modifiers": ["hookAbove"],
        "link": "",
    },
    {
        "name": "U with horn and dot below",
        "majuscule": ("U", "Ự"),
        "minuscule": ("u", "ự"),
        "modifiers": ["horn", "dotBelow"],
        "link": "",
    },
    {
        "name": "U with horn and hook above",
        "majuscule": ("U", "Ử"),
        "minuscule": ("u", "ử"),
        "modifiers": ["horn", "hookAbove"],
        "link": "",
    },
    {
        "name": "U with horn and tilde",
        "majuscule": ("U", "Ữ"),
        "minuscule": ("u", "ữ"),
        "modifiers": ["horn", "tilde"],
        "link": "",
    },
    {
        "name": "U with horn and grave",
        "majuscule": ("U", "Ừ"),
        "minuscule": ("u", "ừ"),
        "modifiers": ["horn", "grave"],
        "link": "",
    },
    {
        "name": "U with horn and acute",
        "majuscule": ("U", "Ứ"),
        "minuscule": ("u", "ứ"),
        "modifiers": ["horn", "acute"],
        "link": "",
    },
    {
        "name": "D with caron",
        "majuscule": ("D", "Ď"),
        "minuscule": ("d", "ď"),
        "modifiers": ["caron"],
        "link": "",
    },
    {
        "name": "U with diaeresis and acute",
        "majuscule": ("U", "Ǘ"),
        "minuscule": ("u", "ǘ"),
        "modifiers": ["diaeresis", "acute"],
        "link": "",
    },
    {
        "name": "U with diaeresis and macron",
        "majuscule": ("U", "Ǖ"),
        "minuscule": ("u", "ǖ"),
        "modifiers": ["diaeresis", "macron"],
        "link": "",
    },
    {
        "name": "U with diaeresis and caron",
        "majuscule": ("U", "Ǚ"),
        "minuscule": ("u", "ǚ"),
        "modifiers": ["diaeresis", "macron"],
        "link": "",
    },
    {
        "name": "U with diaeresis and grave",
        "majuscule": ("U", "Ǜ"),
        "minuscule": ("u", "ǜ"),
        "modifiers": ["diaeresis", "grave"],
        "link": "",
    },
    {
        "name": "A with dot above and macron",
        "majuscule": ("A", "Ǡ"),
        "minuscule": ("a", "ǡ"),
        "modifiers": ["dotAbove", "macron"],
        "link": "",
    },
    {
        "name": "O with ogonek and macron",
        "majuscule": ("O", "Ǭ"),
        "minuscule": ("o", "ǭ"),
        "modifiers": ["ogonek", "macron"],
        "link": "",
    },
    {
        "name": "N with grave",
        "majuscule": ("N", "Ǹ"),
        "minuscule": ("n", "ǹ"),
        "modifiers": ["grave"],
        "link": "",
    },
    {
        "name": "A with double grave",
        "majuscule": ("A", "Ȁ"),
        "minuscule": ("a", "ȁ"),
        "modifiers": ["graveDoubled"],
        "link": "",
    },
    {
        "name": "A with inverted breve",
        "majuscule": ("A", "Ȃ"),
        "minuscule": ("a", "ȃ"),
        "modifiers": ["breveInverted"],
        "link": "",
    },
    {
        "name": "E with double grave",
        "majuscule": ("E", "Ȅ"),
        "minuscule": ("e", "ȅ"),
        "modifiers": ["graveDoubled"],
        "link": "",
    },
    {
        "name": "E with inverted breve",
        "majuscule": ("E", "Ȇ"),
        "minuscule": ("e", "ȇ"),
        "modifiers": ["breveInverted"],
        "link": "",
    },
    {
        "name": "I with double grave",
        "majuscule": ("I", "Ȉ"),
        "minuscule": ("i", "ȉ"),
        "modifiers": ["graveDoubled"],
        "link": "",
    },
    {
        "name": "I with inverted breve",
        "majuscule": ("I", "Ȋ"),
        "minuscule": ("i", "ȋ"),
        "modifiers": ["breveInverted"],
        "link": "",
    },
    {
        "name": "O with double grave",
        "majuscule": ("O", "Ȍ"),
        "minuscule": ("o", "ȍ"),
        "modifiers": ["graveDoubled"],
        "link": "",
    },
    {
        "name": "O with inverted breve",
        "majuscule": ("O", "Ȏ"),
        "minuscule": ("o", "ȏ"),
        "modifiers": ["breveInverted"],
        "link": "",
    },
    {
        "name": "R with double grave",
        "majuscule": ("R", "Ȑ"),
        "minuscule": ("r", "ȑ"),
        "modifiers": ["graveDoubled"],
        "link": "",
    },
    {
        "name": "R with inverted breve",
        "majuscule": ("R", "Ȓ"),
        "minuscule": ("r", "ȓ"),
        "modifiers": ["breveInverted"],
        "link": "",
    },
    {
        "name": "U with double grave",
        "majuscule": ("U", "Ȕ"),
        "minuscule": ("u", "ȕ"),
        "modifiers": ["graveDoubled"],
        "link": "",
    },
    {
        "name": "U with inverted breve",
        "majuscule": ("U", "Ȗ"),
        "minuscule": ("u", "ȗ"),
        "modifiers": ["breveInverted"],
        "link": "",
    },
    {
        "name": "H with caron",
        "majuscule": ("H", "Ȟ"),
        "minuscule": ("h", "ȟ"),
        "modifiers": ["caron"],
        "link": "",
    },
    {
        "name": "A with ring below",
        "majuscule": ("A", "Ḁ"),
        "minuscule": ("a", "ḁ"),
        "modifiers": ["ringBelow"],
        "link": "",
    },
    {
        "name": "B with dot above",
        "majuscule": ("B", "Ḃ"),
        "minuscule": ("b", "ḃ"),
        "modifiers": ["dotAbove"],
        "link": "",
    },
    {
        "name": "B with line below",
        "majuscule": ("B", "Ḇ"),
        "minuscule": ("b", "ḇ"),
        "modifiers": ["lineBelow"],
        "link": "",
    },
    {
        "name": "C with cedilla and acute",
        "majuscule": ("C", "Ḉ"),
        "minuscule": ("c", "ḉ"),
        "modifiers": ["cedilla","acute"],
        "link": "",
    },
    {
        "name": "D with dot above",
        "majuscule": ("D", "Ḋ"),
        "minuscule": ("d", "ḋ"),
        "modifiers": ["dotAbove"],
        "link": "",
    },
    {
        "name": "D with line below",
        "majuscule": ("D", "Ḏ"),
        "minuscule": ("d", "ḏ"),
        "modifiers": ["lineBelow"],
        "link": "",
    },
    {
        "name": "E with macron and grave accent",
        "majuscule": ("E", "Ḕ"),
        "minuscule": ("e", "ḕ"),
        "modifiers": ["macron", "grave"],
        "link": "",
    },
    {
        "name": "E with macron and acute",
        "majuscule": ("E", "Ḗ"),
        "minuscule": ("e", "ḗ"),
        "modifiers": ["macron", "acute"],
        "link": "",
    },
    {
        "name": "E with circumflex below",
        "majuscule": ("E", "Ḙ"),
        "minuscule": ("e", "ḙ"),
        "modifiers": ["circumflexBelow"],
        "link": "",
    },
    {
        "name": "E with tilde below",
        "majuscule": ("E", "Ḛ"),
        "minuscule": ("e", "ḛ"),
        "modifiers": ["tildeBelow"],
        "link": "",
    },
    {
        "name": "E with cedilla and breve",
        "majuscule": ("E", "Ḝ"),
        "minuscule": ("e", "ḝ"),
        "modifiers": ["cedilla", "breve"],
        "link": "",
    },
    {
        "name": "F with dot to above",
        "majuscule": ("F", "Ḟ"),
        "minuscule": ("f", "ḟ"),
        "modifiers": ["dotAbove"],
        "link": "",
    },
    {
        "name": "G with macron",
        "majuscule": ("G", "Ḡ"),
        "minuscule": ("g", "ḡ"),
        "modifiers": ["macron"],
        "link": "",
    },
    {
        "name": "H with dot above",
        "majuscule": ("H", "Ḣ"),
        "minuscule": ("h", "ḣ"),
        "modifiers": ["dotAbove"],
        "link": "",
    },
    {
        "name": "H with diaeresis",
        "majuscule": ("H", "Ḧ"),
        "minuscule": ("h", "ḧ"),
        "modifiers": ["diaeresis"],
        "link": "",
    },
    {
        "name": "H with cedilla",
        "majuscule": ("H", "Ḩ"),
        "minuscule": ("h", "ḩ"),
        "modifiers": ["cedilla"],
        "link": "",
    },
    {
        "name": "H with breve below",
        "majuscule": ("H", "Ḫ"),
        "minuscule": ("h", "ḫ"),
        "modifiers": ["breveBelow"],
        "link": "",
    },
    {
        "name": "I with tilde below",
        "majuscule": ("I", "Ḭ"),
        "minuscule": ("I", "ḭ"),
        "modifiers": ["tildeBelow"],
        "link": "",
    },
    {
        "name": "I with diaeresis and acute",
        "majuscule": ("I", "Ḯ"),
        "minuscule": ("i", "ḯ"),
        "modifiers": ["diaeresis", "acute"],
        "link": "",
    },
    {
        "name": "K with acute",
        "majuscule": ("K", "Ḱ"),
        "minuscule": ("k", "ḱ"),
        "modifiers": ["acute"],
        "link": "",
    },
    {
        "name": "K with dot below",
        "majuscule": ("K", "Ḳ"),
        "minuscule": ("k", "ḳ"),
        "modifiers": ["dotBelow"],
        "link": "",
    },
    {
        "name": "K with line below",
        "majuscule": ("K", "Ḵ"),
        "minuscule": ("k", "ḵ"),
        "modifiers": ["lineBelow"],
        "link": "",
    },
    {
        "name": "L with dot below and macron",
        "majuscule": ("L", "Ḹ"),
        "minuscule": ("l", "ḹ"),
        "modifiers": ["dotBelow", "macron"],
        "link": "",
    },
    {
        "name": "L with line below",
        "majuscule": ("L", "Ḻ"),
        "minuscule": ("l", "ḻ"),
        "modifiers": ["lineBelow"],
        "link": "",
    },
    {
        "name": "M with acute",
        "majuscule": ("M", "Ḿ"),
        "minuscule": ("m", "ḿ"),
        "modifiers": ["acute"],
        "link": "",
    },
    {
        "name": "M with dot above",
        "majuscule": ("M", "Ṁ"),
        "minuscule": ("m", "ṁ"),
        "modifiers": ["dotAbove"],
        "link": "",
    },
    {
        "name": "M with dot below",
        "majuscule": ("M", "Ṃ"),
        "minuscule": ("m", "ṃ"),
        "modifiers": ["dotBelow"],
        "link": "",
    },
    {
        "name": "N with dot below",
        "majuscule": ("N", "Ṇ"),
        "minuscule": ("n", "ṇ"),
        "modifiers": ["dotBelow"],
        "link": "",
    },
    {
        "name": "N with line below",
        "majuscule": ("N", "Ṉ"),
        "minuscule": ("n", "ṉ"),
        "modifiers": ["lineBelow"],
        "link": "",
    },
    {
        "name": "O with tilde and acute",
        "majuscule": ("O", "Ṍ"),
        "minuscule": ("o", "ṍ"),
        "modifiers": ["tilde", "acute"],
        "link": "",
    },
    {
        "name": "O with tilde and diaeresis",
        "majuscule": ("O", "Ṏ"),
        "minuscule": ("o", "ṏ"),
        "modifiers": ["tilde", "diaeresis"],
        "link": "",
    },
    {
        "name": "O with macron and grave",
        "majuscule": ("O", "Ṑ"),
        "minuscule": ("o", "ṑ"),
        "modifiers": ["macron", "grave"],
        "link": "",
    },
    {
        "name": "O with macron and acute",
        "majuscule": ("O", "Ṓ"),
        "minuscule": ("o", "ṓ"),
        "modifiers": ["macron", "acute"],
        "link": "",
    },
    {
        "name": "P with acute",
        "majuscule": ("P", "Ṕ"),
        "minuscule": ("p", "ṕ"),
        "modifiers": ["acute"],
        "link": "",
    },
    {
        "name": "P with dot above",
        "majuscule": ("P", "Ṗ"),
        "minuscule": ("p", "ṗ"),
        "modifiers": ["dotAbove"],
        "link": "",
    },
    {
        "name": "R with dot above",
        "majuscule": ("R", "Ṙ"),
        "minuscule": ("r", "ṙ"),
        "modifiers": ["dotAbove"],
        "link": "",
    },
    {
        "name": "R with dot below and macron",
        "majuscule": ("R", "Ṝ"),
        "minuscule": ("r", "ṝ"),
        "modifiers": ["dotBelow", "macron"],
        "link": "",
    },
    {
        "name": "R with line below",
        "majuscule": ("R", "Ṟ"),
        "minuscule": ("r", "ṟ"),
        "modifiers": ["lineBelow"],
        "link": "",
    },
    {
        "name": "S with dot below",
        "majuscule": ("S", "Ṣ"),
        "minuscule": ("s", "ṣ"),
        "modifiers": ["dotBelow"],
        "link": "",
    },
    {
        "name": "S with acute and dot above",
        "majuscule": ("S", "Ṥ"),
        "minuscule": ("s", "ṥ"),
        "modifiers": ["acute", "dotAbove"],
        "link": "",
    },
    {
        "name": "S with caron and dot above",
        "majuscule": ("S", "Ṧ"),
        "minuscule": ("s", "ṧ"),
        "modifiers": ["caron", "dotAbove"],
        "link": "",
    },
    {
        "name": "S with dot below and dot above",
        "majuscule": ("S", "Ṩ"),
        "minuscule": ("s", "ṩ"),
        "modifiers": ["dotBelow", "dotAbove"],
        "link": "",
    },
    {
        "name": "T with dot above",
        "majuscule": ("T", "Ṫ"),
        "minuscule": ("t", "ṫ"),
        "modifiers": ["dotAbove"],
        "link": "",
    },
    {
        "name": "T with line below",
        "majuscule": ("T", "Ṯ"),
        "minuscule": ("t", "ṯ"),
        "modifiers": ["lineBelow"],
        "link": "",
    },
    {
        "name": "U with diaeresis below",
        "majuscule": ("U", "Ṳ"),
        "minuscule": ("u", "ṳ"),
        "modifiers": ["diaeresisBelow"],
        "link": "",
    },
    {
        "name": "U with tilde below",
        "majuscule": ("U", "Ṵ"),
        "minuscule": ("u", "ṵ"),
        "modifiers": ["tildeBelow"],
        "link": "",
    },
    {
        "name": "U with circumflex below",
        "majuscule": ("U", "Ṷ"),
        "minuscule": ("u", "ṷ"),
        "modifiers": ["circumflexBelow"],
        "link": "",
    },
    {
        "name": "U with tilde and acute",
        "majuscule": ("U", "Ṹ"),
        "minuscule": ("u", "ṹ"),
        "modifiers": ["tilde", "acute"],
        "link": "",
    },
    {
        "name": "U with macron and diaeresis",
        "majuscule": ("U", "Ṻ"),
        "minuscule": ("u", "ṻ"),
        "modifiers": ["macron", "diaeresis"],
        "link": "",
    },
    {
        "name": "V with tilde",
        "majuscule": ("V", "Ṽ"),
        "minuscule": ("v", "ṽ"),
        "modifiers": ["tilde"],
        "link": "",
    },
    {
        "name": "V with dot below",
        "majuscule": ("V", "Ṿ"),
        "minuscule": ("v", "ṿ"),
        "modifiers": ["dotBelow"],
        "link": "",
    },
    {
        "name": "W with dot above",
        "majuscule": ("W", "Ẇ"),
        "minuscule": ("w", "ẇ"),
        "modifiers": ["dotAbove"],
        "link": "",
    },
    {
        "name": "W with dot below",
        "majuscule": ("W", "Ẉ"),
        "minuscule": ("w", "ẉ"),
        "modifiers": ["dotBelow"],
        "link": "",
    },
    {
        "name": "X with diaeresis",
        "majuscule": ("X", "Ẍ"),
        "minuscule": ("x", "ẍ"),
        "modifiers": ["diaeresis"],
        "link": "",
    },
    {
        "name": "Y with dot above",
        "majuscule": ("Y", "Ẏ"),
        "minuscule": ("y", "ẏ"),
        "modifiers": ["dotAbove"],
        "link": "",
    },
    {
        "name": "Z with circumflex",
        "majuscule": ("Z", "Ẑ"),
        "minuscule": ("z", "ẑ"),
        "modifiers": ["circumflex"],
        "link": "",
    },
    {
        "name": "Z with line below",
        "majuscule": ("Z", "Ẕ"),
        "minuscule": ("z", "ẕ"),
        "modifiers": ["lineBelow"],
        "link": "",
    },
    {
        "name": "H with line below",
        "majuscule": None,
        "minuscule": ("h", "ẖ"),
        "modifiers": ["lineBelow"],
        "link": "",
    },
    {
        "name": "T with diaeresis",
        "majuscule": None,
        "minuscule": ("t", "ẗ"),
        "modifiers": ["diaeresis"],
        "link": "",
    },
    {
        "name": "W with ring above",
        "majuscule": None,
        "minuscule": ("w", "ẘ"),
        "modifiers": ["ringAbove"],
        "link": "",
    },
    {
        "name": "Y with ring above",
        "majuscule": None,
        "minuscule": ("y", "ẙ"),
        "modifiers": ["ringAbove"],
        "link": "",
    },
    {
        "name": "J with caron",
        "majuscule": None,
        "minuscule": ("j", "ǰ"),
        "modifiers": ["caron"],
        "link": "",
    },
]

def buildModdedChar (srcDestChars, modStrokes, wraps):
    """
    Takes info surrounding character modification.
    Returns pair of outline and wrapped, modified char.

    srcDestChars: a pair of source/destination characters, like ("a", "á")
    modStrokes: modifier stroke(s) used to get from source to dest
    wraps: lowercase or upper case wrapper pair, like ("{>}{&", "}")

    example:
        >>> buildModdedChar(("a", "á"), "-RP", lowerWraps)
        ("A*/-RP", "{^}{&á}")
    """
    if srcDestChars is None:
        return None
    srcChars, destChar = srcDestChars
    wrapL, wrapR = wraps
    strokes = [latinAlphabet[c] for c in srcChars] + list(modStrokes)
    return ("/".join(strokes), wrapL + destChar + wrapR, destChar)

def createOutlines (entry):
    """
    This just simplifies creating the minuscule and majuscule entries for all
    character modifications. It takes a single entry dictionary, and returns
    two 3-tuples, with outline, translation (wrapped with Plover case stuff),
    and translation character by itself.
    """
    modStrokes = list(map(lambda x: modifiers[x]["outline"], entry["modifiers"]))
    minuscule = buildModdedChar(entry["minuscule"], modStrokes, lowerWraps)
    majuscule = buildModdedChar(entry["majuscule"], modStrokes, upperWraps)
    return (minuscule, majuscule)

def buildFingerspellingDict ():
    spellingDict = {}

    # create definitions for all character modifications
    for entry in entries:
        minuscule, majuscule = createOutlines(entry)
        for scule in [minuscule, majuscule]:
            if scule != None:
                # None means character + case isn't defined in Unicode
                (outline, translation, character) = scule
                spellingDict[outline] = translation

    return spellingDict

if __name__ == "__main__":
    fixSpell = buildFingerspellingDict()

    # dump the dictionary out over stdout
    # NOTE: ensure_ascii=False to stop "á" converting to "\\u00e1", e.g.
    print(json.dumps(fixSpell, ensure_ascii=False, indent=0))

